// backend/src/constants/countryData.ts
// ISO 3166-1 country code mappings and mobile phone number length standards

export const COUNTRY_NAMES: Record<string, string> = {
  "AC": "Ascension Island",
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua & Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia & Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo - Kinshasa",
  "CF": "Central African Republic",
  "CG": "Congo - Brazzaville",
  "CH": "Switzerland",
  "CI": "Côte d’Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong SAR China",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "St. Kitts & Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "St. Pierre & Miquelon",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territories",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "São Tomé & Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TA": "Tristan da Cunha",
  "TC": "Turks & Caicos Islands",
  "TD": "Chad",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Türkiye",
  "TT": "Trinidad & Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "St. Vincent & Grenadines",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis & Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

// Maximum national mobile phone length by ISO 3166-1 country code
export const COUNTRY_PHONE_LENGTHS: Record<string, number> = {
  "AC": 5,
  "AD": 6,
  "AE": 9,
  "AF": 9,
  "AG": 10,
  "AI": 10,
  "AL": 9,
  "AM": 8,
  "AO": 9,
  "AR": 11,
  "AS": 10,
  "AT": 9,
  "AU": 9,
  "AW": 7,
  "AX": 9,
  "AZ": 9,
  "BA": 8,
  "BB": 10,
  "BD": 10,
  "BE": 9,
  "BF": 8,
  "BG": 8,
  "BH": 8,
  "BI": 8,
  "BJ": 10,
  "BL": 9,
  "BM": 10,
  "BN": 7,
  "BO": 8,
  "BQ": 7,
  "BR": 11,
  "BS": 10,
  "BT": 8,
  "BW": 8,
  "BY": 9,
  "BZ": 7,
  "CA": 10,
  "CC": 9,
  "CD": 9,
  "CF": 8,
  "CG": 9,
  "CH": 9,
  "CI": 10,
  "CK": 5,
  "CL": 9,
  "CM": 9,
  "CN": 11,
  "CO": 10,
  "CR": 8,
  "CU": 8,
  "CV": 7,
  "CW": 8,
  "CX": 9,
  "CY": 8,
  "CZ": 9,
  "DE": 11,
  "DJ": 8,
  "DK": 8,
  "DM": 10,
  "DO": 10,
  "DZ": 9,
  "EC": 9,
  "EE": 8,
  "EG": 10,
  "EH": 9,
  "ER": 7,
  "ES": 9,
  "ET": 9,
  "FI": 9,
  "FJ": 7,
  "FK": 5,
  "FM": 7,
  "FO": 6,
  "FR": 9,
  "GA": 8,
  "GB": 10,
  "GD": 10,
  "GE": 9,
  "GF": 9,
  "GG": 10,
  "GH": 9,
  "GI": 8,
  "GL": 6,
  "GM": 7,
  "GN": 9,
  "GP": 9,
  "GQ": 9,
  "GR": 10,
  "GT": 8,
  "GU": 10,
  "GW": 9,
  "GY": 7,
  "HK": 8,
  "HN": 8,
  "HR": 9,
  "HT": 8,
  "HU": 9,
  "ID": 9,
  "IE": 9,
  "IL": 9,
  "IM": 10,
  "IN": 10,
  "IO": 7,
  "IQ": 10,
  "IR": 10,
  "IS": 7,
  "IT": 10,
  "JE": 10,
  "JM": 10,
  "JO": 9,
  "JP": 10,
  "KE": 9,
  "KG": 9,
  "KH": 8,
  "KI": 8,
  "KM": 7,
  "KN": 10,
  "KP": 10,
  "KR": 10,
  "KW": 8,
  "KY": 10,
  "KZ": 10,
  "LA": 10,
  "LB": 8,
  "LC": 10,
  "LI": 9,
  "LK": 9,
  "LR": 9,
  "LS": 8,
  "LT": 8,
  "LU": 9,
  "LV": 8,
  "LY": 9,
  "MA": 9,
  "MC": 9,
  "MD": 8,
  "ME": 8,
  "MF": 9,
  "MG": 9,
  "MH": 7,
  "MK": 8,
  "ML": 8,
  "MM": 8,
  "MN": 8,
  "MO": 8,
  "MP": 10,
  "MQ": 9,
  "MR": 8,
  "MS": 10,
  "MT": 8,
  "MU": 8,
  "MV": 7,
  "MW": 9,
  "MX": 10,
  "MY": 9,
  "MZ": 9,
  "NA": 9,
  "NC": 6,
  "NE": 8,
  "NF": 6,
  "NG": 10,
  "NI": 8,
  "NL": 9,
  "NO": 8,
  "NP": 10,
  "NR": 7,
  "NU": 7,
  "NZ": 9,
  "OM": 8,
  "PA": 8,
  "PE": 9,
  "PF": 8,
  "PG": 8,
  "PH": 10,
  "PK": 10,
  "PL": 9,
  "PM": 6,
  "PR": 10,
  "PS": 9,
  "PT": 9,
  "PW": 7,
  "PY": 9,
  "QA": 8,
  "RE": 9,
  "RO": 9,
  "RS": 9,
  "RU": 10,
  "RW": 9,
  "SA": 9,
  "SB": 7,
  "SC": 7,
  "SD": 9,
  "SE": 9,
  "SG": 8,
  "SH": 5,
  "SI": 8,
  "SJ": 8,
  "SK": 9,
  "SL": 8,
  "SM": 8,
  "SN": 9,
  "SO": 8,
  "SR": 7,
  "SS": 9,
  "ST": 7,
  "SV": 8,
  "SX": 10,
  "SY": 9,
  "SZ": 8,
  "TA": 4,
  "TC": 10,
  "TD": 8,
  "TG": 8,
  "TH": 9,
  "TJ": 9,
  "TK": 4,
  "TL": 8,
  "TM": 8,
  "TN": 8,
  "TO": 7,
  "TR": 10,
  "TT": 10,
  "TV": 6,
  "TW": 9,
  "TZ": 9,
  "UA": 9,
  "UG": 9,
  "US": 10,
  "UY": 8,
  "UZ": 9,
  "VA": 10,
  "VC": 10,
  "VE": 10,
  "VG": 10,
  "VI": 10,
  "VN": 9,
  "VU": 7,
  "WF": 6,
  "WS": 7,
  "XK": 8,
  "YE": 9,
  "YT": 9,
  "ZA": 9,
  "ZM": 9,
  "ZW": 9
};
