// ============================================================
// religionCasteData.ts — Master Religion & Caste Taxonomy
// Extracted from todo-list.xlsx (including SSK under Hindu)
// ============================================================

export interface ReligionEntry {
  label: string;
  value: string;
  castes: string[];
}

export const RELIGION_TAXONOMY: Record<string, ReligionEntry> = {
  "Hindu": {
    "label": "Hindu",
    "value": "Hindu",
    "castes": [
      "24 Manai Telugu Chettiar",
      "96 Kuli Maratha",
      "Aaru Nattu Vellala",
      "Achirapakkam Chettiar",
      "Ad Dharmi",
      "Adi Andhra",
      "Adi Dravidar",
      "Adi Karnataka",
      "Agamudayar / Arcot / Thuluva Vellala",
      "Agaram Vellan Chettiar",
      "Agarwal",
      "Agnikula Kshatriya",
      "Agrahari",
      "Agri",
      "Ahirwar",
      "Ahom",
      "Ambalavasi",
      "Anjana (Chowdary) Patel",
      "Aramari / Gabit",
      "Arekatica",
      "Arora",
      "Arunthathiyar",
      "Arya Vysya",
      "Asathi",
      "Ayira Vysya",
      "Ayodhyavasi",
      "Ayyaraka",
      "Badaga",
      "Baidya",
      "Bairwa",
      "Baishnab",
      "Baishya",
      "Balai",
      "Balija",
      "Balija Naidu",
      "Balija Reddy",
      "Banik",
      "Baniya",
      "Banjara",
      "Barai",
      "Bari",
      "Barnwal",
      "Barujibi",
      "Beri Chettiar",
      "Besta",
      "Bhandari",
      "Bhatia",
      "Bhatraju",
      "Bhavasar Kshatriya",
      "Bhovi",
      "Billava",
      "Bishnoi / Vishnoi",
      "Boyar",
      "Brahmbatt",
      "Brahmin",
      "Brahmin - Anavil",
      "Brahmin - Anaviln Desai",
      "Brahmin - Audichya",
      "Brahmin - Baidhiki / Vaidhiki",
      "Brahmin - Bardai",
      "Brahmin - Barendra",
      "Brahmin - Bhargav",
      "Brahmin - Bhatt",
      "Brahmin - Bhumihar",
      "Brahmin - Dadhich",
      "Brahmin - Daivadnya",
      "Brahmin - Danua",
      "Brahmin - Deshastha",
      "Brahmin - Dhiman",
      "Brahmin - Dravida",
      "Brahmin - Garhwali",
      "Brahmin - Gaur",
      "Brahmin - Goswami / Gosavi",
      "Brahmin - Gujar Gaur",
      "Brahmin - Gurukkal",
      "Brahmin - Halua",
      "Brahmin - Havyaka",
      "Brahmin - Hoysala",
      "Brahmin - Iyengar",
      "Brahmin - Iyer",
      "Brahmin - Jangid",
      "Brahmin - Jhadua",
      "Brahmin - Kanyakubj",
      "Brahmin - Karhade",
      "Brahmin - Khadayata",
      "Brahmin - Khedaval",
      "Brahmin - Kokanastha",
      "Brahmin - Kota",
      "Brahmin - Koteshwara / Kota (Madhwa)",
      "Brahmin - Kulin",
      "Brahmin - Kumoani",
      "Brahmin - Madhwa",
      "Brahmin - Maithil",
      "Brahmin - Mevada",
      "Brahmin - Modh",
      "Brahmin - Mohyal",
      "Brahmin - Nagar",
      "Brahmin - Namboodiri",
      "Brahmin - Narmadiya",
      "Brahmin - Niyogi",
      "Brahmin - Paliwal",
      "Brahmin - Panda",
      "Brahmin - Pandit",
      "Brahmin - Panicker",
      "Brahmin - Pushkarna",
      "Brahmin - Rajgor",
      "Brahmin - Rarhi",
      "Brahmin - Rarhi / Radhi",
      "Brahmin - Rigvedi",
      "Brahmin - Rudraj",
      "Brahmin - Sakaldwipi",
      "Brahmin - Sanadya",
      "Brahmin - Sanketi",
      "Brahmin - Saraswat",
      "Brahmin - Sarua",
      "Brahmin - Saryuparin",
      "Brahmin - Shivalli (Madhva)",
      "Brahmin - Shivhalli",
      "Brahmin - Shri Gaud",
      "Brahmin - Shri Mali",
      "Brahmin - Shrimali",
      "Brahmin - Shukla Yajurvedi",
      "Brahmin - Sikhwal",
      "Brahmin - Smartha",
      "Brahmin - Sri Vaishnava",
      "Brahmin - Stanika",
      "Brahmin - Tapodhan",
      "Brahmin - Tyagi",
      "Brahmin - Vaidiki",
      "Brahmin - Vaikhanasa",
      "Brahmin - Valam",
      "Brahmin - Velanadu",
      "Brahmin - Vyas",
      "Brahmin - Zalora",
      "Bunt (Shetty)",
      "CKP",
      "Caste no bar",
      "Chambhar",
      "Chandravanshi Kahar",
      "Chasa",
      "Chattada Sri Vaishnava",
      "Chaturth",
      "Chaudary",
      "Chaurasia",
      "Cherakula Vellalar",
      "Chettiar",
      "Chhetri",
      "Chippolu (Mera)",
      "Choudhary",
      "Coorgi",
      "Deshmukh",
      "Desikar",
      "Desikar Thanjavur",
      "Devadiga",
      "Devandra Kula Vellalar",
      "Devang Koshthi",
      "Devanga",
      "Devanga Chettiar",
      "Devar / Thevar / Mukkulathor",
      "Dhanak",
      "Dhangar",
      "Dheevara",
      "Dhiman",
      "Dhoba",
      "Dosar / Dusra",
      "Dumal",
      "Dusadh (Paswan)",
      "Ediga",
      "Ediga / Goud (Balija)",
      "Elur Chetty",
      "Ezhava",
      "Ezhava Panicker",
      "Ezhava Thandan",
      "Ezhuthachan",
      "Gabit",
      "Gahoi",
      "Gajula / Kavarai",
      "Ganda",
      "Gandha Vanika",
      "Gandla",
      "Gandla / Ganiga",
      "Ganiga",
      "Garhwali",
      "Gavara",
      "Gawali",
      "Ghisadi",
      "Ghumar",
      "Goala",
      "Goan",
      "Gomantak",
      "Gondhali",
      "Goud",
      "Gounder",
      "Gounder - Kongu Vellala Gounder",
      "Gounder - Nattu Gounder",
      "Gounder - Others",
      "Gounder - Urali Gounder",
      "Gounder - Vanniya Kula Kshatriyar",
      "Gounder - Vettuva Gounder",
      "Gowda",
      "Gowda - Kuruba Gowda",
      "Gramani",
      "Gudia",
      "Gujjar",
      "Gulahre",
      "Gupta",
      "Guptan",
      "Gurav",
      "Gurjar",
      "Haihaivanshi",
      "Hugar (Jeer)",
      "Illaththu Pillai",
      "Intercaste",
      "Irani",
      "Isai Vellalar",
      "Jaalari",
      "Jaiswal",
      "Jandra",
      "Jangam",
      "Jangra",
      "Jangra - Brahmin",
      "Jat",
      "Jatav",
      "Jhadav",
      "Jogi (Nath)",
      "Julaha",
      "Kachara",
      "Kadava Patel",
      "Kahar",
      "Kaibarta",
      "Kaikaala",
      "Kalal",
      "Kalar",
      "Kalinga",
      "Kalinga Vysya",
      "Kalita",
      "Kalwar",
      "Kamboj",
      "Kamma",
      "Kamma Naidu",
      "Kanakkan Padanna",
      "Kandara",
      "Kansari",
      "Kanykubj Bania",
      "Kapu",
      "Kapu Naidu",
      "Kapu Reddy",
      "Karakala Bhakthula",
      "Karana",
      "Karkathar",
      "Karmakar",
      "Karni Bhakthula",
      "Karuneegar",
      "Kasar",
      "Kasaundhan",
      "Kashyap",
      "Kasukara",
      "Katiya",
      "Kavara",
      "Kayastha",
      "Kayastha (Bengali)",
      "Kerala Mudali",
      "Keshri (Kesarwani)",
      "Khandayat",
      "Khandelwal",
      "Kharwar",
      "Khatik",
      "Khatri",
      "Kodikal Pillai",
      "Kokanastha Maratha",
      "Koli",
      "Koli Mahadev",
      "Komti / Arya Vaishya",
      "Kongu Chettiar",
      "Kongu Nadar",
      "Kongu Vellala Gounder",
      "Konkani",
      "Kori",
      "Kori / Koli",
      "Kshatriya",
      "Kshatriya Kurmi",
      "Kshatriya Raju",
      "Kudumbi",
      "Kulal",
      "Kulalar",
      "Kulita",
      "Kumaoni Rajput",
      "Kumawat",
      "Kumbhakar",
      "Kumbhar",
      "Kumhar",
      "Kummari",
      "Kunbi",
      "Kunbi Lonari",
      "Kunbi Maratha",
      "Kunbi Tirale",
      "Kuravan",
      "Kurmi",
      "Kurmi Kshatriya",
      "Kurni",
      "Kuruba",
      "Kuruhina Shetty",
      "Kuruhini Chetty",
      "Kurumbar",
      "Kuruva",
      "Kushwaha (Koiri)",
      "Kutchi",
      "Lad",
      "Lambadi",
      "Leva patel",
      "Leva patil",
      "Linga Balija",
      "Lingayath",
      "Lodhi Rajput",
      "Lohana",
      "Lohar",
      "Lubana",
      "Madhesiya / Kanu / Halwai",
      "Madiga",
      "Madivala / Dhobi",
      "Mahajan",
      "Mahar",
      "Mahendra",
      "Maheshwari",
      "Maheshwari / Meshri",
      "Mahishya",
      "Mahor",
      "Mahuri",
      "Mair Rajput Swarnkar",
      "Majabi",
      "Mala",
      "Mali",
      "Mallah",
      "Malwani",
      "Mangalorean",
      "Manipuri",
      "Manjapudur Chettiar",
      "Mannan / Velan / Vannan",
      "Mapila",
      "Maratha",
      "Maratha Kshatriya",
      "Maruthuvar",
      "Matang",
      "Mathur",
      "Mathur Vaishya",
      "Meena",
      "Meenavar",
      "Meghwal",
      "Mehra",
      "Meru Darji",
      "Mochi",
      "Modak",
      "Modi",
      "Modikarlu",
      "Mogaveera",
      "Mudaliyar",
      "Mudiraj",
      "Munnuru Kapu",
      "Musukama",
      "Muthuraja / Mutharaiyar",
      "Naagavamsam",
      "Nabit",
      "Nadar",
      "Nagaralu",
      "Nai",
      "Naicker",
      "Naicker - Others",
      "Naicker - Vanniya Kula Kshatriyar",
      "Naidu",
      "Naik",
      "Nair",
      "Namasudra / Namassej",
      "Nambiar",
      "Namdarlu",
      "Nanjil Mudali",
      "Nanjil Nattu Vellalar",
      "Nanjil Vellalar",
      "Nanjil pillai",
      "Nankudi Vellalar",
      "Napit",
      "Nattu Gounder",
      "Nattukottai Chettiar",
      "Nayaka",
      "Neeli",
      "Neeli Saali",
      "Nema",
      "Nepali",
      "Nessi",
      "Nhavi",
      "Ontari",
      "Oswal",
      "Otari",
      "Other Brahmins",
      "Others",
      "Othuvaar",
      "Padmasali",
      "Padmashali",
      "Padmavati Porwal",
      "Pagadala",
      "Pal",
      "Pallan / Devandra Kula Vellalan",
      "Panan",
      "Panchal",
      "Pandaram",
      "Pandiya Vellalar",
      "Panicker",
      "Pannirandam Chettiar",
      "Paravan / Bharatar",
      "Parit",
      "Parkava Kulam",
      "Parsi",
      "Partraj",
      "Parvatha Rajakulam",
      "Pasi",
      "Paswan / Dusadh",
      "Patel",
      "Pathare Prabhu",
      "Patil",
      "Patnaick / Sistakaranam",
      "Patra",
      "Pattinavar",
      "Pattusali",
      "Patwa",
      "Perika",
      "Perika / Puragiri Kshatriya",
      "Pillai",
      "Poosala",
      "Porwal",
      "Porwal / Porwar",
      "Poundra",
      "Prajapati",
      "Pulaya / Cheruman",
      "Raigar",
      "Rajaka",
      "Rajastani",
      "Rajbhar",
      "Rajbonshi",
      "Rajput",
      "Ramdasia",
      "Ramgariah",
      "Rastogi",
      "Rathi",
      "Rauniar",
      "Ravidasia",
      "Rawat",
      "Reddy",
      "Relli",
      "Rohit / Chamar",
      "SC",
      "SKP",
      "ST",
      "Sadgope",
      "Sadhu Chetty",
      "Sagara (Uppara)",
      "Saha",
      "Sahu",
      "Saini",
      "Saiva Pillai Thanjavur",
      "Saiva Pillai Tirunelveli",
      "Saliya",
      "Samagar",
      "Sambava",
      "Satnami",
      "Savji",
      "Senai Thalaivar",
      "Senguntha Mudaliyar",
      "Sengunthar / Kaikolar",
      "Settibalija",
      "Setty Balija",
      "Shaw / Sahu / Teli",
      "Shettigar",
      "Shilpkar",
      "Shimpi / Namdev",
      "Sindhi",
      "Sindhi - Amil",
      "Sindhi - Baibhand",
      "Sindhi - Bhanusali",
      "Sindhi - Bhatia",
      "Sindhi - Chhapru",
      "Sindhi - Dadu",
      "Sindhi - Hyderabadi",
      "Sindhi - Larai",
      "Sindhi - Larkana",
      "Sindhi - Lohana",
      "Sindhi - Rohiri",
      "Sindhi - Sahiti",
      "Sindhi - Sakkhar",
      "Sindhi - Sehwani",
      "Sindhi - Shikarpuri",
      "Sindhi - Thatai",
      "Sonar",
      "Soni",
      "Sonkar",
      "Sourashtra",
      "Sozhia Chetty",
      "Sozhiya Vellalar",
      "Srisayana",
      "SSK (Somvanshiy Sahasrarjun Kshatriya)",
      "SAK (Somvanshiy Aarya Kshatriya)",
      "Sugali (Naika)",
      "Sunari",
      "Sundhi",
      "Suthar",
      "Swakula Saali",
      "Swakula Sali",
      "Tamboli",
      "Tanti",
      "Tantubai",
      "Telaga",
      "Teli",
      "Telugupatti",
      "Thakkar",
      "Thakore",
      "Thakur",
      "Thandan",
      "Thigala",
      "Thiyya",
      "Thiyya Thandan",
      "Thogata Veera Kshatriya",
      "Thogata Veerakshathriya",
      "Thondai Mandala Vellalar",
      "Thota",
      "Tili",
      "Togata",
      "Tonk Kshatriya",
      "Turupu Kapu",
      "Ummar / Umre / Bagaria",
      "Urali Gounder",
      "Urs",
      "Vada Balija",
      "Vadambar",
      "Vaddera",
      "Vadugan",
      "Vaish",
      "Vaishnav",
      "Vaishnav Dishaval",
      "Vaishnav Kapol",
      "Vaishnav Khadyata",
      "Vaishnav Lad",
      "Vaishnav Modh",
      "Vaishnav Porvad",
      "Vaishnav Shrimali",
      "Vaishnav Sorathaiya",
      "Vaishnav Vania",
      "Vaishnava",
      "Vaishya",
      "Vaishya Vani",
      "Valluvan",
      "Valmiki",
      "Vani",
      "Vani / Vaishya",
      "Vania",
      "Vaniya",
      "Vaniya Chettiar",
      "Vanjara",
      "Vanjari",
      "Vankar",
      "Vannar",
      "Vannia Kula Kshatriyar",
      "Variar",
      "Varshney",
      "Varshney (Barahseni)",
      "Veera Saivam",
      "Veerakodi Vellala",
      "Velaan",
      "Velama",
      "Vellalar",
      "Vellan Chettiars",
      "Veluthedathu Nair",
      "Vettuva Gounder",
      "Vettuvan",
      "Vijayvargia",
      "Vilakkithala Nair",
      "Vishwakarma",
      "Viswabrahmin",
      "Vokkaliga",
      "Vysya",
      "Yadav",
      "Yadava Naidu",
      "Yellapu"
    ]
  },
  "Muslim - Shia": {
    "label": "Muslim - Shia",
    "value": "Muslim - Shia",
    "castes": [
      "Ansari",
      "Arain",
      "Awan",
      "Bohra",
      "Dekkani",
      "Dudekula",
      "Hanafi",
      "Jat",
      "Khoja",
      "Lebbai",
      "Malik",
      "Mapila",
      "Maraicar",
      "Memon",
      "Mughal",
      "Others",
      "Pathan",
      "Qureshi",
      "Rajput",
      "Rowther",
      "Shafi",
      "Sheikh",
      "Siddiqui",
      "Syed",
      "Unspecified"
    ]
  },
  "Muslim - Sunni": {
    "label": "Muslim - Sunni",
    "value": "Muslim - Sunni",
    "castes": [
      "Ansari",
      "Arain",
      "Awan",
      "Bohra",
      "Dekkani",
      "Dudekula",
      "Hanafi",
      "Jat",
      "Khoja",
      "Lebbai",
      "Malik",
      "Mapila",
      "Maraicar",
      "Memon",
      "Mughal",
      "Others",
      "Pathan",
      "Qureshi",
      "Rajput",
      "Rowther",
      "Shafi",
      "Sheikh",
      "Siddiqui",
      "Syed",
      "Unspecified"
    ]
  },
  "Muslim - Others": {
    "label": "Muslim - Others",
    "value": "Muslim - Others",
    "castes": [
      "Ansari",
      "Arain",
      "Awan",
      "Bohra",
      "Dekkani",
      "Dudekula",
      "Hanafi",
      "Jat",
      "Khoja",
      "Lebbai",
      "Malik",
      "Mapila",
      "Maraicar",
      "Memon",
      "Mughal",
      "Others",
      "Pathan",
      "Qureshi",
      "Rajput",
      "Rowther",
      "Shafi",
      "Sheikh",
      "Siddiqui",
      "Syed",
      "Unspecified"
    ]
  },
  "Christian": {
    "label": "Christian",
    "value": "Christian",
    "castes": [
      "Adventist",
      "Anglican / Episcopal",
      "Anglo-Indian",
      "Apostolic",
      "Assembly of God (AG)",
      "Baptis",
      "Born Again",
      "Brethren",
      "Calvinist",
      "Chaldean Syrian (Assyrian)",
      "Church of Christ",
      "Church of God",
      "Church of North India",
      "Church of South India",
      "Congregational",
      "Evangelist",
      "Jacobite",
      "Jehovah's Witnesses",
      "Knanaya",
      "Knanaya Catholic",
      "Knanaya Jacobite",
      "Latin Catholic",
      "Latter day saints",
      "Lutheran",
      "Malabar Independent Syrian Church",
      "Malankara Catholic",
      "Marthoma",
      "Melkite",
      "Mennonite",
      "Methodist",
      "Moravian",
      "Orthodox",
      "Others",
      "Pentecost",
      "Presbyterian",
      "Protestant",
      "Reformed Baptist",
      "Reformed Presbyterian",
      "Roman Catholic",
      "Seventh-day Adventist",
      "St. Thomas Evangelical",
      "Syrian Catholic",
      "Syrian Jacobite",
      "Syrian Orthodox",
      "Syro Malabar"
    ]
  },
  "Sikh": {
    "label": "Sikh",
    "value": "Sikh",
    "castes": [
      "Ahluwalia",
      "Arora",
      "Bhatia",
      "Bhatra",
      "Ghumar",
      "Intercaste",
      "Jat",
      "Kamboj",
      "Khatri",
      "Kshatriya",
      "Lubana",
      "Majabi",
      "Nai",
      "Others",
      "Rai",
      "Rajput",
      "Ramdasia",
      "Ramgharia",
      "Ravidasia",
      "Saini",
      "Tonk Kshatriya",
      "Unspecified"
    ]
  },
  "Jain - Digambar": {
    "label": "Jain - Digambar",
    "value": "Jain - Digambar",
    "castes": [
      "Agarwal",
      "Asati",
      "Ayodhyavasi",
      "Bagherwal",
      "Bania",
      "Barhiya",
      "Charanagare",
      "Chaturtha",
      "Dhakada",
      "Gahoi / Grihapati",
      "Golalare / Kharaua",
      "Golapurva",
      "Golsinghare",
      "Harada",
      "Humad / Humbad",
      "Intercaste",
      "Jaiswal",
      "KVO",
      "Kambhoja",
      "Kasar",
      "Kathanere",
      "Khandelwal",
      "Kharaua",
      "Kutchi",
      "Lamechu",
      "Nema",
      "Oswal",
      "Others",
      "Padmavati Porwal",
      "Palliwal",
      "Panchama",
      "Parmar",
      "Parwar / Paravara",
      "Porwad / Porwal",
      "Porwal",
      "Saitwal",
      "Samanar / Nayinar",
      "Samiya",
      "Sarak",
      "Shrimal",
      "Unspecified",
      "Upadhyaya",
      "Vaishya",
      "Veerwal"
    ]
  },
  "Jain - Shwetambar": {
    "label": "Jain - Shwetambar",
    "value": "Jain - Shwetambar",
    "castes": [
      "Agarwal",
      "Asati",
      "Ayodhyavasi",
      "Bagherwal",
      "Bania",
      "Barhiya",
      "Charanagare",
      "Chaturtha",
      "Dhakada",
      "Gahoi / Grihapati",
      "Golalare / Kharaua",
      "Golapurva",
      "Golsinghare",
      "Harada",
      "Humad / Humbad",
      "Intercaste",
      "Jaiswal",
      "KVO",
      "Kambhoja",
      "Kasar",
      "Kathanere",
      "Khandelwal",
      "Kharaua",
      "Kutchi",
      "Lamechu",
      "Nema",
      "Oswal",
      "Others",
      "Padmavati Porwal",
      "Palliwal",
      "Panchama",
      "Parmar",
      "Parwar / Paravara",
      "Porwad / Porwal",
      "Porwal",
      "Saitwal",
      "Samanar / Nayinar",
      "Samiya",
      "Sarak",
      "Shrimal",
      "Unspecified",
      "Upadhyaya",
      "Vaishya",
      "Veerwal"
    ]
  },
  "Jain - Others": {
    "label": "Jain - Others",
    "value": "Jain - Others",
    "castes": [
      "Agarwal",
      "Asati",
      "Ayodhyavasi",
      "Bagherwal",
      "Bania",
      "Barhiya",
      "Charanagare",
      "Chaturtha",
      "Dhakada",
      "Gahoi / Grihapati",
      "Golalare / Kharaua",
      "Golapurva",
      "Golsinghare",
      "Harada",
      "Humad / Humbad",
      "Intercaste",
      "Jaiswal",
      "KVO",
      "Kambhoja",
      "Kasar",
      "Kathanere",
      "Khandelwal",
      "Kharaua",
      "Kutchi",
      "Lamechu",
      "Nema",
      "Oswal",
      "Others",
      "Padmavati Porwal",
      "Palliwal",
      "Panchama",
      "Parmar",
      "Parwar / Paravara",
      "Porwad / Porwal",
      "Porwal",
      "Saitwal",
      "Samanar / Nayinar",
      "Samiya",
      "Sarak",
      "Shrimal",
      "Unspecified",
      "Upadhyaya",
      "Vaishya",
      "Veerwal"
    ]
  },
  "Parsi": {
    "label": "Parsi",
    "value": "Parsi",
    "castes": [
      "Intercaste",
      "Irani",
      "Others",
      "Parsi"
    ]
  },
  "Buddhist": {
    "label": "Buddhist",
    "value": "Buddhist",
    "castes": [
      "Neo Buddhist",
      "Others",
      "Tibetan Buddhist"
    ]
  },
  "Jewish": {
    "label": "Jewish",
    "value": "Jewish",
    "castes": [
      "Neo Buddhist",
      "Others",
      "Tibetan Buddhist"
    ]
  },
  "Inter-Religion": {
    "label": "Inter-Religion",
    "value": "Inter-Religion",
    "castes": [
      "Ad Dharmi",
      "Adi Andhra",
      "Adi Dravidar",
      "Adi Karnataka",
      "Agarwal",
      "Agnikula Kshatriya",
      "Agri",
      "Ahir Shimpi",
      "Ahom",
      "Ambalavasi",
      "Arekatica",
      "Arora",
      "Arunthathiyar",
      "Arya Vysya",
      "Ayyaraka",
      "Badaga",
      "Baidya",
      "Baishnab",
      "Baishya",
      "Balija",
      "Banik",
      "Baniya",
      "Banjara",
      "Barai",
      "Bari",
      "Barujibi",
      "Besta",
      "Bhandari",
      "Bhatia",
      "Bhatraju",
      "Bhavasar Kshatriya",
      "Bhovi",
      "Billava",
      "Bishnoi / Vishnoi",
      "Born Again",
      "Boyar",
      "Brahmbatt",
      "Brahmin",
      "Brahmin - Anavil",
      "Brahmin - Audichya",
      "Brahmin - Barendra",
      "Brahmin - Bhatt",
      "Brahmin - Bhumihar",
      "Brahmin - Daivadnya",
      "Brahmin - Danua",
      "Brahmin - Deshastha",
      "Brahmin - Dhiman",
      "Brahmin - Dravida",
      "Brahmin - Garhwali",
      "Brahmin - Gaur",
      "Brahmin - Goswami / Gosavi",
      "Brahmin - Gujar Gaur",
      "Brahmin - Gurukkal",
      "Brahmin - Halua",
      "Brahmin - Havyaka",
      "Brahmin - Hoysala",
      "Brahmin - Iyengar",
      "Brahmin - Iyer",
      "Brahmin - Jangid",
      "Brahmin - Jhadua",
      "Brahmin - Kanyakubj",
      "Brahmin - Karhade",
      "Brahmin - Kokanastha",
      "Brahmin - Kota",
      "Brahmin - Kulin",
      "Brahmin - Kumaoni",
      "Brahmin - Madhwa",
      "Brahmin - Maithil",
      "Brahmin - Modh",
      "Brahmin - Mohyal",
      "Brahmin - Nagar",
      "Brahmin - Namboodiri",
      "Brahmin - Narmadiya",
      "Brahmin - Niyogi",
      "Brahmin - Paliwal",
      "Brahmin - Panda",
      "Brahmin - Pandit",
      "Brahmin - Pushkarna",
      "Brahmin - Rarhi",
      "Brahmin - Rigvedi",
      "Brahmin - Rudraj",
      "Brahmin - Sakaldwipi",
      "Brahmin - Sanadya",
      "Brahmin - Sanketi",
      "Brahmin - Saraswat",
      "Brahmin - Saryuparin",
      "Brahmin - Shivhalli",
      "Brahmin - Shrimali",
      "Brahmin - Sikhwal",
      "Brahmin - Smartha",
      "Brahmin - Sri Vaishnava",
      "Brahmin - Stanika",
      "Brahmin - Tyagi",
      "Brahmin - Vaidiki",
      "Brahmin - Vaikhanasa",
      "Brahmin - Velanadu",
      "Brahmin - Vyas",
      "Brethren",
      "Bunt (Shetty)",
      "CKP",
      "Chambhar",
      "Chandravanshi Kahar",
      "Chasa",
      "Chattada Sri Vaishnava",
      "Chaudary",
      "Chaurasia",
      "Chettiar",
      "Chhetri",
      "Chippolu (Mera)",
      "Christian",
      "Christian - Others",
      "Church of South India",
      "Coorgi",
      "Devadiga",
      "Devandra Kula Vellalar",
      "Devang Koshthi",
      "Devanga",
      "Devar / Thevar / Mukkulathor",
      "Dhangar",
      "Dheevara",
      "Dhiman",
      "Dhoba",
      "Dumal",
      "Dusadh (Paswan)",
      "Ediga",
      "Evangelist",
      "Ezhava",
      "Ezhuthachan",
      "Gabit",
      "Ganda",
      "Gandla",
      "Ganiga",
      "Garhwali",
      "Gavara",
      "Gawali",
      "Ghisadi",
      "Ghumar",
      "Goala",
      "Goan",
      "Gomantak",
      "Gondhali",
      "Goud",
      "Gounder",
      "Gowda",
      "Gramani",
      "Gudia",
      "Gujjar",
      "Gupta",
      "Guptan",
      "Gurav",
      "Gurjar",
      "Hugar (Jeer)",
      "Intercaste",
      "Irani",
      "Jaalari",
      "Jacobite",
      "Jain",
      "Jain - Agarwal",
      "Jain - Asati",
      "Jain - Ayodhyavasi",
      "Jain - Bagherwal",
      "Jain - Bania",
      "Jain - Barhiya",
      "Jain - Charanagare",
      "Jain - Chaturtha",
      "Jain - Dhakada",
      "Jain - Gahoi / Grihapati",
      "Jain - Golalare / Kharaua",
      "Jain - Golapurva",
      "Jain - Golsinghare",
      "Jain - Harada",
      "Jain - Humad / Humbad",
      "Jain - Intercaste",
      "Jain - Jaiswal",
      "Jain - KVO",
      "Jain - Kambhoja",
      "Jain - Kasar",
      "Jain - Kathanere",
      "Jain - Khandelwal",
      "Jain - Kharaua",
      "Jain - Kutchi",
      "Jain - Lamechu",
      "Jain - Nema",
      "Jain - Oswal",
      "Jain - Others",
      "Jain - Padmavati Porwal",
      "Jain - Palliwal",
      "Jain - Panchama",
      "Jain - Parmar",
      "Jain - Parwar / Paravara",
      "Jain - Porwad / Porwal",
      "Jain - Porwal",
      "Jain - Saitwal",
      "Jain - Samanar / Nayinar",
      "Jain - Samiya",
      "Jain - Sarak",
      "Jain - Shrimal",
      "Jain - Unspecified",
      "Jain - Upadhyaya",
      "Jain - Vaishya",
      "Jain - Veerwal",
      "Jaiswal",
      "Jandra",
      "Jangam",
      "Jangra",
      "Jangra - Brahmin",
      "Jat",
      "Jatav",
      "Jogi (Nath)",
      "Kachara",
      "Kadava Patel",
      "Kahar",
      "Kaibarta",
      "Kalal",
      "Kalanji",
      "Kalar",
      "Kalinga",
      "Kalinga Vysya",
      "Kalita",
      "Kalwar",
      "Kamboj",
      "Kamma",
      "Kansari",
      "Kapu",
      "Karana",
      "Karmakar",
      "Karuneegar",
      "Kasar",
      "Kashyap",
      "Katiya",
      "Kayastha",
      "Kayastha (Bengali)",
      "Khandayat",
      "Khandelwal",
      "Kharwar",
      "Khatri",
      "Knanaya",
      "Knanaya Catholic",
      "Knanaya Jacobite",
      "Kokanastha Maratha",
      "Koli",
      "Koli Mahadev",
      "Kongu Vellala Gounder",
      "Konkani",
      "Kori",
      "Kshatriya",
      "Kudumbi",
      "Kulal",
      "Kulalar",
      "Kulita",
      "Kumawat",
      "Kumbhakar",
      "Kumbhar",
      "Kumhar",
      "Kummari",
      "Kunbi",
      "Kuravan",
      "Kurmi",
      "Kurmi / Kurmi Kshatriya",
      "Kuruba",
      "Kuruhina Shetty",
      "Kurumbar",
      "Kushwaha (Koiri)",
      "Kutchi",
      "Lambadi",
      "Latin Catholic",
      "Leva patel",
      "Leva patil",
      "Lingayath",
      "Lodhi Rajput",
      "Lohana",
      "Lohar",
      "Lubana",
      "Madiga",
      "Madivala / Dhobi",
      "Mahajan",
      "Mahar",
      "Mahendra",
      "Maheshwari",
      "Mahishya",
      "Majabi",
      "Mala",
      "Malankara Catholic",
      "Mali",
      "Mallah",
      "Mangalorean",
      "Manipuri",
      "Mapila",
      "Maratha",
      "Marthoma",
      "Maruthuvar",
      "Matang",
      "Mathur",
      "Meena",
      "Meenavar",
      "Mehra",
      "Meru Darji",
      "Mochi",
      "Modak",
      "Mogaveera",
      "Mudaliyar",
      "Mudiraj",
      "Munnuru Kapu",
      "Muslim",
      "Muslim - Ansari",
      "Muslim - Arain",
      "Muslim - Awan",
      "Muslim - Bohra",
      "Muslim - Dekkani",
      "Muslim - Dudekula",
      "Muslim - Hanafi",
      "Muslim - Jat",
      "Muslim - Khoja",
      "Muslim - Lebbai",
      "Muslim - Malik",
      "Muslim - Mapila",
      "Muslim - Maraicar",
      "Muslim - Memon",
      "Muslim - Mughal",
      "Muslim - Others",
      "Muslim - Pathan",
      "Muslim - Qureshi",
      "Muslim - Rajput",
      "Muslim - Rowther",
      "Muslim - Shafi",
      "Muslim - Sheikh",
      "Muslim - Siddiqui",
      "Muslim - Syed",
      "Muslim - Unspecified",
      "Muthuraja / Mutharaiyar",
      "Naagavamsam",
      "Nadar",
      "Nagaralu",
      "Nai / Nayi Brahmin",
      "Naicker",
      "Naidu",
      "Naik",
      "Nair",
      "Namasudra / Namassej",
      "Nambiar",
      "Napit",
      "Nayaka",
      "Neeli",
      "Nepali",
      "Nhavi",
      "Oswal",
      "Otari",
      "Other Brahmins",
      "Others",
      "Padmasali",
      "Pal",
      "Panchal",
      "Pandaram",
      "Panicker",
      "Parkavakulam / Udayar",
      "Parsi",
      "Partraj",
      "Pasi",
      "Patel",
      "Pathare Prabhu",
      "Patnaick / Sistakaranam",
      "Patra",
      "Pentecost",
      "Perika",
      "Pillai",
      "Poosala",
      "Porwal",
      "Prajapati",
      "Raigar",
      "Rajaka / Vannar",
      "Rajastani",
      "Rajbhar",
      "Rajbonshi",
      "Rajput",
      "Ramdasia",
      "Ramgariah",
      "Ravidasia",
      "Rawat",
      "Reddy",
      "Relli",
      "Roman Catholic",
      "SC",
      "SKP",
      "ST",
      "Sadgope",
      "Sagara (Uppara)",
      "Saha",
      "Sahu",
      "Saini",
      "Saliya",
      "Savji",
      "Senai Thalaivar",
      "Senguntha Mudaliyar",
      "Settibalija",
      "Shimpi / Namdev",
      "Sikh",
      "Sikh - Ahluwalia",
      "Sikh - Arora",
      "Sikh - Bhatia",
      "Sikh - Bhatra",
      "Sikh - Ghumar",
      "Sikh - Intercaste",
      "Sikh - Jat",
      "Sikh - Kamboj",
      "Sikh - Khatri",
      "Sikh - Kshatriya",
      "Sikh - Lubana",
      "Sikh - Majabi",
      "Sikh - Nai",
      "Sikh - Others",
      "Sikh - Rai",
      "Sikh - Rajput",
      "Sikh - Ramdasia",
      "Sikh - Ramgharia",
      "Sikh - Ravidasia",
      "Sikh - Saini",
      "Sikh - Tonk Kshatriya",
      "Sikh - Unspecified",
      "Sindhi",
      "Sindhi - Amil",
      "Sindhi - Baibhand",
      "Sindhi - Bhanusali",
      "Sindhi - Bhatia",
      "Sindhi - Chhapru",
      "Sindhi - Dadu",
      "Sindhi - Hyderabadi",
      "Sindhi - Larai",
      "Sindhi - Larkana",
      "Sindhi - Lohana",
      "Sindhi - Rohiri",
      "Sindhi - Sahiti",
      "Sindhi - Sakkhar",
      "Sindhi - Sehwani",
      "Sindhi - Shikarpuri",
      "Sindhi - Thatai",
      "Sonar",
      "Soni",
      "Sourashtra",
      "Sozhiya Vellalar",
      "Srisayana",
      "Sugali (Naika)",
      "Sunari",
      "Sundhi",
      "Suthar",
      "Swakula Sali",
      "Syrian Catholic",
      "Syrian Jacobite",
      "Syrian Orthodox",
      "Syro Malabar",
      "Tamboli",
      "Tanti",
      "Tantubai",
      "Telaga",
      "Teli",
      "Thakkar",
      "Thakore",
      "Thakur",
      "Thigala",
      "Thiyya",
      "Tili",
      "Togata",
      "Tonk Kshatriya",
      "Turupu Kapu",
      "Urali Gounder",
      "Urs",
      "Vada Balija",
      "Vaddera",
      "Vaish",
      "Vaishnav",
      "Vaishnava",
      "Vaishya",
      "Vaishya Vani",
      "Valluvan",
      "Valmiki",
      "Vania",
      "Vaniya",
      "Vanjara",
      "Vanjari",
      "Vankar",
      "Vannar",
      "Vannia Kula Kshatriyar",
      "Variar",
      "Varshney",
      "Veera Saivam",
      "Velaan",
      "Velama",
      "Vellalar",
      "Veluthedathu Nair",
      "Vettuva Gounder",
      "Vilakkithala Nair",
      "Vishwakarma",
      "Viswabrahmin",
      "Vokkaliga",
      "Vysya",
      "Yadav",
      "Yellapu"
    ]
  }
};

export const RELIGION_ALIASES: Record<string, string> = {
  "Hinduism": "Hindu",
  "Islam": "Muslim - Sunni",
  "Muslim": "Muslim - Sunni",
  "Christianity": "Christian",
  "Sikhism": "Sikh",
  "Jainism": "Jain - Digambar",
  "Jain": "Jain - Digambar",
  "Buddhism": "Buddhist",
  "Zoroastrianism": "Parsi",
  "Parsi / Zoroastrian": "Parsi"
};

export const POPULAR_RELIGIONS = [
  'Hindu',
  'Muslim',
  'Christian',
  'Sikh',
  'Jain',
  'Buddhist',
  'Parsi',
  'Other',
];

export const RELIGIONS: Array<{ label: string; value: string }> = [
  { label: 'Hindu', value: 'Hindu' },
  { label: 'Muslim - Sunni', value: 'Muslim - Sunni' },
  { label: 'Muslim - Shia', value: 'Muslim - Shia' },
  { label: 'Muslim - Others', value: 'Muslim - Others' },
  { label: 'Christian', value: 'Christian' },
  { label: 'Sikh', value: 'Sikh' },
  { label: 'Jain - Digambar', value: 'Jain - Digambar' },
  { label: 'Jain - Shwetambar', value: 'Jain - Shwetambar' },
  { label: 'Jain - Others', value: 'Jain - Others' },
  { label: 'Buddhist', value: 'Buddhist' },
  { label: 'Parsi', value: 'Parsi' },
  { label: 'Jewish', value: 'Jewish' },
  { label: 'Inter-Religion', value: 'Inter-Religion' },
  { label: 'Other', value: 'Other' },
];

export function resolveReligionKey(religion: string | undefined | null): string | null {
  if (!religion) return null;
  const trimmed = religion.trim();
  if (RELIGION_TAXONOMY[trimmed]) return trimmed;
  if (RELIGION_ALIASES[trimmed] && RELIGION_TAXONOMY[RELIGION_ALIASES[trimmed]]) {
    return RELIGION_ALIASES[trimmed];
  }
  return null;
}

/**
 * Returns all castes for a selected religion.
 */
export function getCastesForReligion(religion: string | undefined | null): Array<{ label: string; value: string }> {
  const key = resolveReligionKey(religion);
  if (!key || !RELIGION_TAXONOMY[key]) return [{ label: 'Other', value: 'Other' }];

  const castesList = RELIGION_TAXONOMY[key].castes;
  const list = castesList.map((caste) => ({
    label: caste,
    value: caste,
  }));

  list.push({ label: 'Other', value: 'Other' });
  return list;
}

// Kept for backwards compatibility if referenced anywhere
export function getSubcastesForCaste(
  religion: string | undefined | null,
  caste: string | undefined | null
): Array<{ label: string; value: string }> {
  return [];
}

export function hasPredefinedSubcastes(
  religion: string | undefined | null,
  caste: string | undefined | null
): boolean {
  return false;
}
