// prisma/seed.js
require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const { Pool } = require('pg');

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is not set in .env');
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const relationTypes = [
  // UP (Generation +)
  { code: 'AJI_SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NAT_JAVAI' },
  { code: 'AJI_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NAT_JAVAI' },
  { code: 'AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'PANAAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'AAI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'MULGA' },
  { code: 'VADIL', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'MULGA' },
  { code: 'SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'JAVAI' },
  { code: 'SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'JAVAI' },
  { code: 'KAKA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'PUTANYA' },
  { code: 'KAKI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'PUTANYA' },
  { code: 'MAMA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'MAMI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'AATYA', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'FUA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'MAVSHI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'MAVSA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'CHULTA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'PUTANYA' },
  { code: 'CHULTI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'PUTANYA' },
  { code: 'SAVATR_VADIL', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'SAVATR_MULGA' },
  { code: 'SAVATR_AAI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'SAVATR_MULGA' },
  { code: 'PP_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 4, reciprocalCode: 'PP_NATU' },
  { code: 'PP_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 4, reciprocalCode: 'PP_NAAT' },
  { code: 'PPP_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 5, reciprocalCode: 'PPP_NATU' },
  { code: 'PPP_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 5, reciprocalCode: 'PPP_NAAT' },
  { code: 'AJOBA_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NAT_JAVAI' },
  { code: 'AJOBA_SASU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NAT_JAVAI' },
  { code: 'MAMA_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'JAVAI' },
  { code: 'MAMI_SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'JAVAI' },
  { code: 'PANAJI_SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTU_JAVAI' },
  { code: 'PANJOBA_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU_JAVAI' },
  { code: 'CHULAT_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'PUTAN_JAVAI' },
  { code: 'ATYA_SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHOCHA_JAVAI' },
  { code: 'MAVAS_SASU', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHOCHA_JAVAI' },

  // SAME (Generation 0)
  { code: 'NAVRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'BAYKO' },
  { code: 'BAYKO', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NAVRA' },
  { code: 'BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'BHAU' },
  { code: 'BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'BHAU' },
  { code: 'VAHINI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DIR_CHOTE' },
  { code: 'DAJI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MEVHANA' },
  { code: 'MEVHANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'DAJI' },
  { code: 'MEVHANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DAJI' },
  { code: 'DIR_CHOTE', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'DIR_MOTHE', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'CHULAT_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'CHULAT_BHAU' },
  { code: 'CHULAT_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'CHULAT_BHAU' },
  { code: 'ATYE_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MAMI_BHAU' },
  { code: 'ATYE_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'MAMI_BHAU' },
  { code: 'MAV_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MAV_BHAU' },
  { code: 'MAV_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'MAV_BHAU' },
  { code: 'MAMI_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'ATYE_BHAU' },
  { code: 'MAMI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'ATYE_BHAU' },
  { code: 'CHULAT_DAJI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MEVHANA' },
  { code: 'CHULAT_VAHINI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DIR_CHOTE' },
  { code: 'MAMI_DAJI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MEVHANA' },
  { code: 'MAMI_VAHINI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DIR_CHOTE' },
  { code: 'MAV_DAJI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MEVHANA' },
  { code: 'MAV_VAHINI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DIR_CHOTE' },
  { code: 'NANAND', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'NANANDOI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'CHULTA_DIR', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'CHULTA_NANAND', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'SAVATR_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'SAVATR_BHAU' },
  { code: 'SAVATR_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'SAVATR_BHAU' },
  { code: 'SADU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'SADU' },

  // DOWN (Generation -)
  { code: 'MULGA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'VADIL' },
  { code: 'MULGI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'VADIL' },
  { code: 'SAVATR_MULGA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'SAVATR_VADIL' },
  { code: 'SAVATR_MULGI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'SAVATR_VADIL' },
  { code: 'JAVAI', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'SASRA' },
  { code: 'SUN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'SASRA' },
  { code: 'PUTANYA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'KAKA' },
  { code: 'PUTANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'KAKA' },
  { code: 'BHACHA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'MAMA' },
  { code: 'BHACHI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'MAMA' },
  { code: 'BHACHI_SUN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'SASRA' },
  { code: 'JAVAIBHACHA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'SASRA' },
  { code: 'NATU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -2, reciprocalCode: 'AJOBA' },
  { code: 'NAAT', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -2, reciprocalCode: 'AJOBA' },
  { code: 'NAT_JAVAI', category: 'FAMILY', targetGender: 'MALE', treeLevel: -2, reciprocalCode: 'AAJI' },
  { code: 'NATASUN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -2, reciprocalCode: 'AAJI' },
  { code: 'PANTU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -3, reciprocalCode: 'PANAAJI' },
  { code: 'PANTI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -3, reciprocalCode: 'PANAAJI' },
  { code: 'PANTISUN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -3, reciprocalCode: 'PANTU' },
  { code: 'PANTU_JAVAI', category: 'FAMILY', targetGender: 'MALE', treeLevel: -3, reciprocalCode: 'PANTI' },
  { code: 'PP_NATU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -4, reciprocalCode: 'PP_AJOBA' },
  { code: 'PP_NAAT', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -4, reciprocalCode: 'PP_AJOBA' },
  { code: 'PPP_NATU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -5, reciprocalCode: 'PPP_AJOBA' },
  { code: 'PPP_NAAT', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -5, reciprocalCode: 'PPP_AJOBA' },

  // FRIENDS
  { code: 'MITRA', category: 'FRIEND', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'MITRA' },
  { code: 'MAITRIN', category: 'FRIEND', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'MAITRIN' },

  // GENERIC RELATIVE (catch-all — family tree only)
  { code: 'NATEVAIK', category: 'FAMILY', targetGender: null, treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  // NEW EXTENDED & IN-LAW RELATIONS
  { code: 'BHAUJAI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'DIR_CHOTE' },
  { code: 'CHULAT_MEVHANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'BHAUJAI' },
  { code: 'CHULAT_MEVHANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'BHAUJAI' },
  { code: 'MAMI_SASRA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'JAVAI' },
  { code: 'CHULAT_NANAND', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'CHULAT_BHAUJAI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'CHULTA_DIR' },
  { code: 'CHULAT_PUTANYA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'KAKA' },
  { code: 'CHULAT_PUTANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'KAKA' },
  { code: 'CHULAT_BHACHA', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'MAMA' },
  { code: 'CHULAT_BHACHI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'MAMA' },
  { code: 'NANA_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'NATU' },
  { code: 'NANI_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'NAAT' },
  { code: 'MAMI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'MAMI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'AATYA_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'FUA_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'FAU_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_AATYA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'CHULAT_AATYA_BHAU' },
  { code: 'CHULAT_AATYA_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'CHULAT_AATYA_BHAU' },
  { code: 'DAJI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'DAJI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'MAME_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAME_AAJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAME_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAMI_AJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAVAS_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAV_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAV_AAJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'NANA_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'NAAT' },
  { code: 'CHULAT_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'AATYA_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAME_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAMI_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAVAS_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_MAMA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'CHULAT_MAVSHI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'FUA_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'KAKI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'KAKI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'CHULAT_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'AATYA_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTI' },
  { code: 'KHAPAR_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 4, reciprocalCode: 'PP_NATU' },
  { code: 'KHAPAR_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 4, reciprocalCode: 'PP_NAAT' },
  { code: 'MAME_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'MAVAS_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTI' },
  { code: 'AATYA_KHAPAR_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 4, reciprocalCode: 'PP_NAAT' },
  { code: 'CHULAT_KHAPAR_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 4, reciprocalCode: 'PP_NATU' },
  { code: 'MAME_KHAPAR_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 4, reciprocalCode: 'PP_NATU' },
  { code: 'MAVAS_KHAPAR_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 4, reciprocalCode: 'PP_NAAT' },
  { code: 'SUNRI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'MEVHANA' },
  { code: 'SUNRI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'SUNRI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'SADU_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'SADU_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'NANANDOI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'NANANDOI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'CHULAT_SUN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'KAKA' },
  { code: 'VYAHI', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'VYAHI' },
  { code: 'VIHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'VIHIN' },
  { code: 'SUN_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'NATEVAIK' },
  { code: 'SUN_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'NATEVAIK' },
  { code: 'JAVAI_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: -1, reciprocalCode: 'NATEVAIK' },
  { code: 'JAVAI_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: -1, reciprocalCode: 'NATEVAIK' },
  { code: 'CHULAT_DIR', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'VAHINI' },
  { code: 'MAVSA_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'MAVSA_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'FUA_CHA_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'FUA_CHI_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'NATEVAIK' },
  { code: 'CHULAT_MAMI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'CHULAT_MAVSHA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 1, reciprocalCode: 'BHACHA' },
  { code: 'CHULAT_MAME_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'CHULAT_MAME_BHAU' },
  { code: 'CHULAT_MAME_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'CHULAT_MAME_BHAU' },
  { code: 'CHULAT_MAV_BHAU', category: 'FAMILY', targetGender: 'MALE', treeLevel: 0, reciprocalCode: 'CHULAT_MAV_BHAU' },
  { code: 'CHULAT_MAV_BAHIN', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 0, reciprocalCode: 'CHULAT_MAV_BHAU' },
  { code: 'MAMI_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAME_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'FAU_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAVSA_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'KHAPAR_NANA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 4, reciprocalCode: 'PP_NATU' },
  { code: 'KHAPAR_NANI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 4, reciprocalCode: 'PP_NAAT' },
  { code: 'CHULAT_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTI' },
  { code: 'FUA_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'CHULAT_AATYA_AAJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'CHULAT_AATYA_AAJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 2, reciprocalCode: 'NATU' },
  { code: 'MAVSHI_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTI' },
  { code: 'MAVSA_PANJOBA', category: 'FAMILY', targetGender: 'MALE', treeLevel: 3, reciprocalCode: 'PANTU' },
  { code: 'MAMI_PANJI', category: 'FAMILY', targetGender: 'FEMALE', treeLevel: 3, reciprocalCode: 'PANTI' },
];

const translations = [
// UP
  { code: 'AJI_SASU', mr: 'आजीसासू', en: 'Grandmother-in-law', zh: '外曾祖母 (配偶方)' },
  { code: 'AJI_SASRA', mr: 'आजीसासरा', en: 'Grandfather-in-law', zh: '外曾祖父 (配偶方)' },
  { code: 'AAJI', mr: 'आजी', en: 'Grandmother', zh: '祖母 / 外祖母' },
  { code: 'AJOBA', mr: 'आजोबा', en: 'Grandfather', zh: '祖父 / 外祖父' },
  { code: 'NANI', mr: 'नानी', en: 'Maternal Grandmother', zh: '外祖母' },
  { code: 'NANA', mr: 'नाना', en: 'Maternal Grandfather', zh: '外祖父' },
  { code: 'PANAAJI', mr: 'पणजी', en: 'Great Grandmother', zh: '曾祖母' },
  { code: 'PANJOBA', mr: 'पणजोबा', en: 'Great Grandfather', zh: '曾祖父' },
  { code: 'AAI', mr: 'आई', en: 'Mother', zh: '母亲' },
  { code: 'VADIL', mr: 'वडील', en: 'Father', zh: '父亲' },
  { code: 'SASU', mr: 'सासू', en: 'Mother-in-law', zh: '岳母 / 婆婆' },
  { code: 'SASRA', mr: 'सासरा', en: 'Father-in-law', zh: '岳父 / 公公' },
  { code: 'KAKA', mr: 'काका', en: 'Paternal Uncle', zh: '叔叔 / 伯伯' },
  { code: 'KAKI', mr: 'काकी', en: 'Paternal Aunt', zh: '婶婶 / 伯母' },
  { code: 'MAMA', mr: 'मामा', en: 'Maternal Uncle', zh: '舅舅' },
  { code: 'MAMI', mr: 'मामी', en: 'Maternal Aunt', zh: '舅妈' },
  { code: 'AATYA', mr: 'आत्या', en: 'Paternal Aunt', zh: '姑姑' },
  { code: 'FUA', mr: 'फुआ', en: 'Paternal Uncle (Husband of Aatya)', zh: '姑父' },
  { code: 'MAVSHI', mr: 'मावशी', en: 'Maternal Aunt', zh: '阿姨' },
  { code: 'MAVSA', mr: 'मावसा', en: 'Maternal Uncle (Husband of Mavshi)', zh: '姨夫' },
  { code: 'CHULTA', mr: 'चुलता', en: 'Uncle', zh: '叔伯' },
  { code: 'CHULTI', mr: 'चुलती', en: 'Aunt', zh: '婶母' },
  { code: 'SAVATR_VADIL', mr: 'सावत्रवडील', en: 'Step-Father', zh: '继父' },
  { code: 'SAVATR_AAI', mr: 'सावत्रआई', en: 'Step-Mother', zh: '继母' },
  { code: 'PP_AJOBA', mr: 'खापर पणजोबा', en: 'Great-Great Grandfather', zh: '高祖父' },
  { code: 'PP_AAJI', mr: 'खापर पणजी', en: 'Great-Great Grandmother', zh: '高祖母' },
  { code: 'PPP_AJOBA', mr: 'थोर खापर पणजोबा', en: 'Great-Great-Great Grandfather', zh: '天祖父' },
  { code: 'PPP_AAJI', mr: 'थोर खापर पणजी', en: 'Great-Great-Great Grandmother', zh: '天祖母' },
  { code: 'AJOBA_SASRA', mr: 'आजोबासासरा', en: 'Grandfather-in-law', zh: '祖父 (配偶方)' },
  { code: 'AJOBA_SASU', mr: 'आजोबासासू', en: 'Grandfather-in-law', zh: '祖母 (配偶方)' },
  { code: 'MAMA_SASRA', mr: 'मामासासरा', en: 'Uncle-in-law (Maternal)', zh: '舅舅 (配偶方)' },
  { code: 'MAMI_SASU', mr: 'मामीसासू', en: 'Aunt-in-law (Maternal)', zh: '舅妈 (配偶方)' },
  { code: 'PANAJI_SASU', mr: 'पणजीसासू', en: 'Great-grandmother-in-law', zh: '曾祖母 (配偶方)' },
  { code: 'PANJOBA_SASRA', mr: 'पणजोबासासरा', en: 'Great-grandfather-in-law', zh: '曾祖父 (配偶方)' },
  { code: 'CHULAT_SASRA', mr: 'चुलत सासरा', en: 'Paternal Uncle-in-law', zh: '堂叔父 (配偶方)' },
  { code: 'ATYA_SASU', mr: 'आत्या सासू', en: 'Paternal Aunt-in-law', zh: '姑姑 (配偶方)' },
  { code: 'MAVAS_SASU', mr: 'मावस सासू', en: 'Maternal Aunt-in-law', zh: '阿姨 (配偶方)' },

  // SAME
  { code: 'NAVRA', mr: 'नवरा', en: 'Husband', zh: '丈夫' },
  { code: 'BAYKO', mr: 'बायको', en: 'Wife', zh: '妻子' },
  { code: 'BHAU', mr: 'भाऊ', en: 'Brother', zh: '兄弟' },
  { code: 'BAHIN', mr: 'बहीण', en: 'Sister', zh: '姐妹' },
  { code: 'VAHINI', mr: 'वहिनी', en: 'Sister-in-law', zh: '嫂子 / 弟媳' },
  { code: 'DAJI', mr: 'दाजी', en: 'Brother-in-law', zh: '姐夫 / 妹夫' },
  { code: 'MEVHANA', mr: 'मेव्हणा', en: 'Brother-in-law (Wife/Husband Brother)', zh: '内兄 / 内弟 (妻子或丈夫的兄弟)' },
  { code: 'MEVHANI', mr: 'मेव्हणी', en: 'Sister-in-law (Wife/Husband Sister)', zh: '大姨子 / 小姨子 (妻子或丈夫的姐妹)' },
  { code: 'DIR_CHOTE', mr: 'दिर-छोटे', en: 'Brother-in-law (Younger)', zh: '小叔子' },
  { code: 'DIR_MOTHE', mr: 'दिर-मोठे', en: 'Brother-in-law (Elder)', zh: '大伯子' },
  { code: 'CHULAT_BHAU', mr: 'चुलतभाऊ', en: 'Paternal Cousin Brother', zh: '堂兄弟' },
  { code: 'CHULAT_BAHIN', mr: 'चुलतबहीण', en: 'Paternal Cousin Sister', zh: '堂姐妹' },
  { code: 'ATYE_BHAU', mr: 'आत्येभाऊ', en: 'Paternal Aunt Son', zh: '表兄弟 (姑母之子)' },
  { code: 'ATYE_BAHIN', mr: 'आत्येबहीण', en: 'Paternal Aunt Daughter', zh: '表姐妹 (姑母之女)' },
  { code: 'MAV_BHAU', mr: 'मावसभाऊ', en: 'Maternal Aunt Son', zh: '表兄弟 (姨母之子)' },
  { code: 'MAV_BAHIN', mr: 'मावसबहीण', en: 'Maternal Aunt Daughter', zh: '表姐妹 (姨母之女)' },
  { code: 'MAMI_BHAU', mr: 'मामेभाऊ', en: 'Maternal Uncle Son', zh: '表兄弟 (舅父之子)' },
  { code: 'MAMI_BAHIN', mr: 'मामेबहीण', en: 'Maternal Uncle Daughter', zh: '表姐妹 (舅父之女)' },
  { code: 'CHULAT_DAJI', mr: 'चुलत दाजी', en: "Paternal Cousin Sister's Husband", zh: '堂姐夫/堂妹夫' },
  { code: 'CHULAT_VAHINI', mr: 'चुलत वहिनी', en: "Paternal Cousin Brother's Wife", zh: '堂嫂/堂弟媳' },
  { code: 'MAMI_DAJI', mr: 'मामे दाजी', en: "Maternal Cousin Sister's Husband", zh: '表姐夫/表妹夫' },
  { code: 'MAMI_VAHINI', mr: 'मामे वहिनी', en: "Maternal Cousin Brother's Wife", zh: '表嫂/表弟媳' },
  { code: 'MAV_DAJI', mr: 'मावस दाजी', en: "Maternal Aunt Cousin Sister's Husband", zh: '姨表姐夫/姨表妹夫' },
  { code: 'MAV_VAHINI', mr: 'मावस वहिनी', en: "Maternal Aunt Cousin Brother's Wife", zh: '姨表嫂/姨表弟媳' },
  { code: 'NANAND', mr: 'नणंद', en: "Husband's Sister", zh: '大姑子 / 小姑子' },
  { code: 'NANANDOI', mr: 'नणंदोई', en: "Husband of Nanand", zh: '姑夫 (丈夫的姐妹的丈夫)' },
  { code: 'CHULTA_DIR', mr: 'चुलतदीर', en: 'Cousin-in-law brother', zh: '堂叔子 (堂兄弟的丈夫)' },
  { code: 'CHULTA_NANAND', mr: 'चुलतनणंद', en: 'Cousin-in-law sister', zh: '堂姑子 (堂姐妹的丈夫)' },
  { code: 'SAVATR_BHAU', mr: 'सावत्रभाऊ', en: 'Step-Brother', zh: '继兄弟' },
  { code: 'SAVATR_BAHIN', mr: 'सावत्रबहीण', en: 'Step-Sister', zh: '继姐妹' },
  { code: 'SADU', mr: 'साडू', en: "Wife's sister's husband", zh: '连襟 (妻子的姐妹的丈夫)' },

  // DOWN
  { code: 'MULGA', mr: 'मुलगा', en: 'Son', zh: '儿子' },
  { code: 'MULGI', mr: 'मुलगी', en: 'Daughter', zh: '女儿' },
  { code: 'JAVAI', mr: 'जावई', en: 'Son-in-law', zh: '女婿' },
  { code: 'SUN', mr: 'सुन', en: 'Daughter-in-law', zh: '儿媳' },
  { code: 'PUTANYA', mr: 'पुतण्या', en: 'Nephew', zh: '侄子' },
  { code: 'PUTANI', mr: 'पुतणी', en: 'Niece', zh: '侄女' },
  { code: 'BHACHA', mr: 'भाचा', en: 'Nephew (Sister/Brother Child)', zh: '外甥 (姐妹/兄弟之子)' },
  { code: 'BHACHI', mr: 'भाची', en: 'Niece (Sister/Brother Child)', zh: '外甥女 (姐妹/兄弟之女)' },
  { code: 'BHACHI_SUN', mr: 'भाची सून', en: "Nephew's Wife", zh: '外甥媳妇' },
  { code: 'JAVAIBHACHA', mr: 'भाची जावई', en: "Niece's Husband", zh: '外甥女婿' },
  { code: 'SAVATR_MULGA', mr: 'सावत्रमुलगा', en: 'Step-Son', zh: '继子' },
  { code: 'SAVATR_MULGI', mr: 'सावत्रमुलगी', en: 'Step-Daughter', zh: '继女' },
  { code: 'NATU', mr: 'नातू', en: 'Grandson', zh: '孙子' },
  { code: 'NAAT', mr: 'नात', en: 'Granddaughter', zh: '孙女' },
  { code: 'NAT_JAVAI', mr: 'नातजावई', en: 'Grandson-in-law', zh: '孙女婿' },
  { code: 'NATASUN', mr: 'नातसुन', en: 'Granddaughter-in-law', zh: '孙媳妇' },
  { code: 'PANTU', mr: 'पणतू', en: 'Great Grandson', zh: '曾孙' },
  { code: 'PANTI', mr: 'पणती', en: 'Great Granddaughter', zh: '曾孙女' },
  { code: 'PANTISUN', mr: 'पणतीसून', en: 'Great Granddaughter-in-law', zh: '曾孙媳' },
  { code: 'PANTU_JAVAI', mr: 'पणतूजावई', en: 'Great Grandson-in-law', zh: '曾孙女婿' },
  { code: 'PP_NATU', mr: 'खापर नातू', en: 'Great-Great Grandson', zh: '玄孙' },
  { code: 'PP_NAAT', mr: 'खापर नात', en: 'Great-Great Granddaughter', zh: '玄孙女' },
  { code: 'PPP_NATU', mr: 'थोर खापर नातू', en: 'Great-Great-Great Grandson', zh: '来孙' },
  { code: 'PPP_NAAT', mr: 'थोर खापर नात', en: 'Great-Great-Great Granddaughter', zh: '来孙女' },

  // FRIENDS
  { code: 'MITRA', mr: 'मित्र', en: 'Friend (Male)', zh: '朋友 (男)' },
  { code: 'MAITRIN', mr: 'मैत्रीण', en: 'Friend (Female)', zh: '朋友 (女)' },

  // GENERIC RELATIVE
  { code: 'NATEVAIK', mr: 'नातेवाईक', en: 'Relative', zh: '亲戚' },

  { code: 'BHAUJAI', mr: 'भाऊजय', en: 'Brother Wife', zh: '嫂子/弟媳' },
  { code: 'CHULAT_MEVHANA', mr: 'चुलत मेव्हणा', en: 'Cousin Brother-in-law', zh: '堂/表内兄/弟' },
  { code: 'CHULAT_MEVHANI', mr: 'चुलत मेव्हणी', en: 'Cousin Sister-in-law', zh: '堂/表大姨/小姨' },
  { code: 'MAMI_SASRA', mr: 'मामी सासरा', en: 'Maternal Uncle-in-law', zh: '舅岳父' },
  { code: 'CHULAT_NANAND', mr: 'चुलत नणंद', en: 'Cousin Sister-in-law', zh: '堂/表小姑' },
  { code: 'CHULAT_BHAUJAI', mr: 'चुलत भाऊजय', en: 'Cousin Brother Wife', zh: '堂/表嫂' },
  { code: 'CHULAT_PUTANYA', mr: 'चुलत पुतण्या', en: 'Cousin Nephew', zh: '堂侄' },
  { code: 'CHULAT_PUTANI', mr: 'चुलत पुतणी', en: 'Cousin Niece', zh: '堂侄女' },
  { code: 'CHULAT_BHACHA', mr: 'चुलत भाचा', en: 'Cousin Nephew', zh: '堂/表外甥' },
  { code: 'CHULAT_BHACHI', mr: 'चुलत भाची', en: 'Cousin Niece', zh: '堂/表外甥女' },
  { code: 'NANA_PANJOBA', mr: 'नाना पणजोबा', en: 'Maternal Great-Grandfather', zh: '外曾祖父' },
  { code: 'NANI_PANJI', mr: 'नानी पणजी', en: 'Maternal Great-Grandmother', zh: '外曾祖母' },
  { code: 'MAMI_CHA_BHAU', mr: 'मामीचा भाऊ', en: 'Mami Brother', zh: '舅母兄弟' },
  { code: 'MAMI_CHI_BAHIN', mr: 'मामीची बहीण', en: 'Mami Sister', zh: '舅母姐妹' },
  { code: 'AATYA_AAJI', mr: 'आत्या आजी', en: 'Grand Aunt', zh: '姑祖母' },
  { code: 'FUA_AJOBA', mr: 'फुआ आजोबा', en: 'Grand Uncle (Grand-Aunt Husband)', zh: '姑祖父' },
  { code: 'FAU_AJOBA', mr: 'फुआ आजोबा', en: 'Grand Uncle (Grand-Aunt Husband)', zh: '姑祖父' },
  { code: 'CHULAT_AJOBA', mr: 'चुलत आजोबा', en: 'Grand Uncle', zh: '堂祖父' },
  { code: 'CHULAT_AAJI', mr: 'चुलत आजी', en: 'Cousin Grandmother', zh: '堂祖母' },
  { code: 'CHULAT_AATYA_BHAU', mr: 'चुलत आत्येभाऊ', en: 'Cousin Brother (Grand-Aunt Son)', zh: '表兄弟' },
  { code: 'CHULAT_AATYA_BAHIN', mr: 'चुलत आत्येबहीण', en: 'Cousin Sister (Grand-Aunt Daughter)', zh: '表姐妹' },
  { code: 'DAJI_CHA_BHAU', mr: 'दाजीचा भाऊ', en: 'Daji Brother', zh: '姐夫兄弟' },
  { code: 'DAJI_CHI_BAHIN', mr: 'दाजीची बहीण', en: 'Daji Sister', zh: '姐夫姐妹' },
  { code: 'MAME_AJOBA', mr: 'मामे आजोबा', en: 'Grand Maternal Uncle', zh: '舅祖父' },
  { code: 'MAME_AAJOBA', mr: 'मामे आजोबा', en: 'Grand Maternal Uncle', zh: '舅祖父' },
  { code: 'MAME_AAJI', mr: 'मामे आजी', en: 'Grand Maternal Aunt', zh: '舅祖母' },
  { code: 'MAMI_AJOBA', mr: 'मामे आजोबा', en: 'Grand Maternal Uncle', zh: '舅祖父' },
  { code: 'MAVAS_AAJI', mr: 'मावस आजी', en: 'Grand Maternal Aunt', zh: '姨祖母' },
  { code: 'MAV_AAJI', mr: 'मावस आजी', en: 'Grand Maternal Aunt', zh: '姨祖母' },
  { code: 'MAV_AAJOBA', mr: 'मावस आजोबा', en: 'Grand Maternal Uncle', zh: '姨祖父' },
  { code: 'NANA_PANJI', mr: 'नाना पणजी', en: 'Maternal Great-Grandmother', zh: '外曾祖母' },
  { code: 'CHULAT_NANA', mr: 'चुलत नाना', en: 'Cousin Nana', zh: '堂外祖父' },
  { code: 'AATYA_NANI', mr: 'आत्या नानी', en: 'Cousin Nani', zh: '堂外祖母' },
  { code: 'MAME_NANA', mr: 'मामे नाना', en: 'Mame Nana', zh: '舅外祖父' },
  { code: 'MAMI_NANA', mr: 'मामे नाना', en: 'Mame Nana', zh: '舅外祖父' },
  { code: 'MAVAS_NANI', mr: 'मावस नानी', en: 'Mavas Nani', zh: '姨外祖母' },
  { code: 'CHULAT_NANI', mr: 'चुलत नानी', en: 'Cousin Nani', zh: '堂外祖母' },
  { code: 'CHULAT_MAMA', mr: 'चुलत मामा', en: 'Cousin Maternal Uncle', zh: '堂舅' },
  { code: 'CHULAT_MAVSHI', mr: 'चुलत मावशी', en: 'Cousin Maternal Aunt', zh: '堂姨' },
  { code: 'FUA_NANA', mr: 'फुआ नाना', en: 'Fua Nana', zh: '姑外祖父' },
  { code: 'KAKI_CHA_BHAU', mr: 'काकीचा भाऊ', en: 'Kaki Brother', zh: '婶母兄弟' },
  { code: 'KAKI_CHI_BAHIN', mr: 'काकीची बहीण', en: 'Kaki Sister', zh: '婶母姐妹' },
  { code: 'CHULAT_PANJOBA', mr: 'चुलत पणजोबा', en: 'Cousin Great-Grandfather', zh: '堂曾祖父' },
  { code: 'AATYA_PANJI', mr: 'आत्या पणजी', en: 'Cousin Great-Grandmother', zh: '姑曾祖母' },
  { code: 'KHAPAR_PANJOBA', mr: 'खापर पणजोबा', en: 'Great-Great-Grandfather', zh: '高祖父' },
  { code: 'KHAPAR_PANJI', mr: 'खापर पणजी', en: 'Great-Great-Grandmother', zh: '高祖母' },
  { code: 'MAME_PANJOBA', mr: 'मामे पणजोबा', en: 'Mame Great-Grandfather', zh: '舅曾祖父' },
  { code: 'MAVAS_PANJI', mr: 'मावस पणजी', en: 'Mavas Great-Grandmother', zh: '姨曾祖母' },
  { code: 'AATYA_KHAPAR_PANJI', mr: 'आत्या खापर पणजी', en: 'Aatya Great-Great-Grandmother', zh: '姑高祖母' },
  { code: 'CHULAT_KHAPAR_PANJOBA', mr: 'चुलत खापर पणजोबा', en: 'Chulat Great-Great-Grandfather', zh: '堂高祖父' },
  { code: 'MAME_KHAPAR_PANJOBA', mr: 'मामे खापर पणजोबा', en: 'Mame Great-Great-Grandfather', zh: '舅高祖父' },
  { code: 'MAVAS_KHAPAR_PANJI', mr: 'मावस खापर पणजी', en: 'Mavas Great-Great-Grandmother', zh: '姨高祖母' },
  { code: 'SUNRI', mr: 'सुनरी', en: 'Sister-in-law', zh: '妻弟媳/妻兄媳' },
  { code: 'SUNRI_CHA_BHAU', mr: 'सुनरीचा भाऊ', en: 'Sunri Brother', zh: '内弟媳兄弟' },
  { code: 'SUNRI_CHI_BAHIN', mr: 'सुनरीची बहीण', en: 'Sunri Sister', zh: '内弟媳姐妹' },
  { code: 'SADU_CHA_BHAU', mr: 'साडूचा भाऊ', en: 'Sadu Brother', zh: '连襟兄弟' },
  { code: 'SADU_CHI_BAHIN', mr: 'साडूची बहीण', en: 'Sadu Sister', zh: '连襟姐妹' },
  { code: 'NANANDOI_CHA_BHAU', mr: 'नणंदोईचा भाऊ', en: 'Nanandoi Brother', zh: '姑爷兄弟' },
  { code: 'NANANDOI_CHI_BAHIN', mr: 'नणंदोईची बहीण', en: 'Nanandoi Sister', zh: '姑爷姐妹' },
  { code: 'CHULAT_SUN', mr: 'चुलत सून', en: 'Cousin Daughter-in-law', zh: '堂儿媳' },
  { code: 'VYAHI', mr: 'व्याही', en: "Child's Father-in-law / Co-in-law (Male)", zh: '亲家公' },
  { code: 'VIHIN', mr: 'विहीण', en: "Child's Mother-in-law / Co-in-law (Female)", zh: '亲家母' },
  { code: 'SUN_CHA_BHAU', mr: 'सुनेचा भाऊ', en: "Daughter-in-law's Brother", zh: '儿媳兄弟' },
  { code: 'SUN_CHI_BAHIN', mr: 'सुनेची बहीण', en: "Daughter-in-law's Sister", zh: '儿媳姐妹' },
  { code: 'JAVAI_CHA_BHAU', mr: 'जावयाचा भाऊ', en: "Son-in-law's Brother", zh: '女婿兄弟' },
  { code: 'JAVAI_CHI_BAHIN', mr: 'जावयाची बहीण', en: "Son-in-law's Sister", zh: '女婿姐妹' },
  { code: 'CHULAT_DIR', mr: 'चुलत दीर', en: "Husband's Paternal Cousin Brother", zh: '堂大伯/堂小叔' },
  { code: 'MAVSA_CHA_BHAU', mr: 'मावशाचा भाऊ', en: "Mavsa's Brother", zh: '姨父兄弟' },
  { code: 'MAVSA_CHI_BAHIN', mr: 'मावशाची बहीण', en: "Mavsa's Sister", zh: '姨父姐妹' },
  { code: 'FUA_CHA_BHAU', mr: 'फुवाचा भाऊ', en: "Fua's Brother", zh: '姑父兄弟' },
  { code: 'FUA_CHI_BAHIN', mr: 'फुवाची बहीण', en: "Fua's Sister", zh: '姑父姐妹' },
  { code: 'CHULAT_MAMI', mr: 'चुलत मामी', en: 'Cousin Maternal Aunt (Wife of Chulat Mama)', zh: '堂舅母' },
  { code: 'CHULAT_MAVSHA', mr: 'चुलत मावसा', en: 'Cousin Maternal Uncle (Husband of Chulat Mavshi)', zh: '堂姨夫' },
  { code: 'CHULAT_MAME_BHAU', mr: 'चुलत मामेभाऊ', en: 'Cousin Brother (Chulat Mama Son)', zh: '表兄弟' },
  { code: 'CHULAT_MAME_BAHIN', mr: 'चुलत मामेबहीण', en: 'Cousin Sister (Chulat Mama Daughter)', zh: '表姐妹' },
  { code: 'CHULAT_MAV_BHAU', mr: 'चुलत मावसभाऊ', en: 'Cousin Brother (Chulat Mavshi Son)', zh: '表兄弟' },
  { code: 'CHULAT_MAV_BAHIN', mr: 'चुलत मावसबहीण', en: 'Cousin Sister (Chulat Mavshi Daughter)', zh: '表姐妹' },
  { code: 'MAMI_NANI', mr: 'मामी नानी', en: 'Mami Nani', zh: '舅外祖母' },
  { code: 'MAME_NANI', mr: 'मामे नानी', en: 'Mame Nani', zh: '舅外祖母' },
  { code: 'FAU_NANA', mr: 'फुआ नाना', en: 'Fau Nana', zh: '姑外祖父' },
  { code: 'MAVSA_NANA', mr: 'मावसा नाना', en: 'Mavsa Nana', zh: '姨外祖父' },
  { code: 'KHAPAR_NANA', mr: 'खापर नाना', en: 'Maternal Great-Great Grandfather', zh: '外高祖父' },
  { code: 'KHAPAR_NANI', mr: 'खापर नानी', en: 'Maternal Great-Great Grandmother', zh: '外高祖母' },
  { code: 'CHULAT_PANJI', mr: 'चुलत पणजी', en: 'Cousin Great-Grandmother', zh: '堂曾祖母' },
  { code: 'FUA_PANJOBA', mr: 'फुआ पणजोबा', en: 'Great-Granduncle (Husband of Aatya Panji)', zh: '姑曾祖父' },
  { code: 'CHULAT_AATYA_AAJOBA', mr: 'चुलत आत्या आजोबा', en: 'Cousin Granduncle (Aatya Panji Son)', zh: '表伯公' },
  { code: 'CHULAT_AATYA_AAJI', mr: 'चुलत आत्या आजी', en: 'Cousin Grandaunt (Aatya Panji Daughter)', zh: '表姑婆' },
  { code: 'MAVSHI_PANJI', mr: 'मावशी पणजी', en: 'Maternal Great-Grandaunt', zh: '姨曾祖母' },
  { code: 'MAVSA_PANJOBA', mr: 'मावसा पणजोबा', en: 'Maternal Great-Granduncle (Husband of Mavshi Panji)', zh: '姨曾祖父' },
  { code: 'MAMI_PANJI', mr: 'मामी पणजी', en: 'Maternal Great-Grandaunt (Wife of Mame Panjoba)', zh: '舅曾祖母' },
];

const TRANSLATION_LANGUAGE_CODES = ['mr', 'en', 'hi', 'ta', 'kn', 'gu', 'te', 'zh'];

const relationLanguageOverrides = {
  hi: {
    AAI: 'माँ', VADIL: 'पिता', AAJI: 'दादी', AJOBA: 'दादा', NANI: 'नानी', NANA: 'नाना',
    PANAAJI: 'परदादी', PANJOBA: 'परदादा', SASU: 'सास', SASRA: 'ससुर', KAKA: 'चाचा', KAKI: 'चाची',
    MAMA: 'मामा', MAMI: 'मामी', AATYA: 'बुआ', FUA: 'फूफा', MAVSHI: 'मौसी', MAVSA: 'मौसा',
    NAVRA: 'पति', BAYKO: 'पत्नी', BHAU: 'भाई', BAHIN: 'बहन', VAHINI: 'भाभी', DAJI: 'जीजा',
    MEVHANA: 'साला', MEVHANI: 'साली', DIR_CHOTE: 'देवर', DIR_MOTHE: 'जेठ', NANAND: 'ननद', NANANDOI: 'नंदोई',
    MULGA: 'बेटा', MULGI: 'बेटी', JAVAI: 'दामाद', SUN: 'बहू', PUTANYA: 'भतीजा', PUTANI: 'भतीजी',
    BHACHA: 'भांजा', BHACHI: 'भांजी', NATU: 'पोता', NAAT: 'पोती', MITRA: 'मित्र', MAITRIN: 'सखी', NATEVAIK: 'रिश्तेदार',
    SAVATR_VADIL: 'सौतेले पिता', SAVATR_AAI: 'सौतेली माँ', SAVATR_BHAU: 'सौतेला भाई', SAVATR_BAHIN: 'सौतेली बहन',
    SAVATR_MULGA: 'सौतेला बेटा', SAVATR_MULGI: 'सौतेली बेटी', CHULAT_BHAU: 'चचेरा भाई', CHULAT_BAHIN: 'चचेरी बहन',
    MAMI_BHAU: 'ममेरा भाई', MAMI_BAHIN: 'ममेरी बहन', MAV_BHAU: 'मौसेरा भाई', MAV_BAHIN: 'मौसेरी बहन',
    CHULAT_DAJI: 'चचेरा जीजा', CHULAT_VAHINI: 'चचेरी भाभी', MAMI_DAJI: 'ममेरा जीजा', MAMI_VAHINI: 'ममेरी भाभी', MAV_DAJI: 'मौसेरा जीजा', MAV_VAHINI: 'मौसेरी भाभी',
    CHULAT_BHACHA: 'चचेरा भांजा', CHULAT_BHACHI: 'चचेरी भांजी',
    CHULAT_AAJI: 'चचेरी दादी', CHULAT_AATYA_BHAU: 'फुफेरा भाई', CHULAT_AATYA_BAHIN: 'फुफेरी बहन',
    FUA_AJOBA: 'फूफा दादा', FAU_AJOBA: 'फूफा दादा',
    ATYE_BHAU: 'फुफेरा भाई', ATYE_BAHIN: 'फुफेरी बहन', AJI_SASU: 'दादी सास', AJI_SASRA: 'दादा ससुर',
    CHULTA: 'चाचा', CHULTI: 'चाची', PP_AJOBA: 'परदादा', PP_AAJI: 'परदादी', PPP_AJOBA: 'लक्कड़ दादा',
    PPP_AAJI: 'लक्कड़ दादी', AJOBA_SASRA: 'दादा ससुर', AJOBA_SASU: 'दादी सास', MAMA_SASRA: 'मामा ससुर',
    MAMI_SASU: 'मामी सास', PANAJI_SASU: 'परदादी सास', PANJOBA_SASRA: 'परदादा ससुर', CHULAT_SASRA: 'चाचा ससुर',
    ATYA_SASU: 'बुआ सास', MAVAS_SASU: 'मौसी सास', CHULTA_DIR: 'चचेरा देवर', CHULTA_NANAND: 'चचेरी ननद',
    CHULAT_PANJI: 'चचेरी परदादी', FUA_PANJOBA: 'फूफा परदादा', CHULAT_AATYA_AAJOBA: 'फुफेरा दादा', CHULAT_AATYA_AAJI: 'फुफेरी दादी', MAVSHI_PANJI: 'मौसी परदादी', MAVSA_PANJOBA: 'मौसा परदादा', MAMI_PANJI: 'मामी परदादी',
    NAT_JAVAI: 'नाती दामाद', NATASUN: 'नाती बहू', PANTU: 'परपोता', PANTI: 'परपोती', PANTISUN: 'परपोत बहू',
    PANTU_JAVAI: 'परपोता दामाद', PP_NATU: 'लक्कड़ पोता', PP_NAAT: 'लक्कड़ पोती', PPP_NATU: 'छक्कड़ पोता', PPP_NAAT: 'छक्कड़ पोती'
  },
  ta: {
    AAI: 'அம்மா', VADIL: 'அப்பா', AAJI: 'பாட்டி', AJOBA: 'தாத்தா', NANI: 'நானி', NANA: 'நானா',
    PANAAJI: 'பெரிய பாட்டி', PANJOBA: 'பெரிய தாத்தா', SASU: 'மாமியார்', SASRA: 'மாமனார்', KAKA: 'சித்தப்பா', KAKI: 'சித்தி',
    MAMA: 'மாமா', MAMI: 'மாமி', AATYA: 'அத்தை', FUA: 'அத்தை மாமா', MAVSHI: 'மௌசி', MAVSA: 'மௌசா',
    NAVRA: 'கணவர்', BAYKO: 'மனைவி', BHAU: 'அண்ணன்', BAHIN: 'சகோதரி', VAHINI: 'அண்ணி', DAJI: 'மச்சான்',
    MEVHANA: 'மைத்துனர்', MEVHANI: 'மைத்துனி', DIR_CHOTE: 'இளைய மைத்துனர்', DIR_MOTHE: 'மூத்த மைத்துனர்',
    NANAND: 'நந்தி', NANANDOI: 'நந்தோய்', MULGA: 'மகன்', MULGI: 'மகள்', JAVAI: 'மருமகன்', SUN: 'மருமகள்',
    PUTANYA: 'சகோதரர் மகன்', PUTANI: 'சகோதரர் மகள்', BHACHA: 'சகோதரி மகன்', BHACHI: 'சகோதரி மகள்',
    NATU: 'பேரன்', NAAT: 'பேத்தி', MITRA: 'நண்பன்', MAITRIN: 'நண்பி', NATEVAIK: 'உறவினர்', SAVATR_VADIL: 'மாற்றுத் தந்தை',
    SAVATR_AAI: 'மாற்றுத் தாய்', SAVATR_BHAU: 'மாற்றுச் சகோதரன்', SAVATR_BAHIN: 'மாற்றுச் சகோதரி',
    SAVATR_MULGA: 'மாற்று மகன்', SAVATR_MULGI: 'மாற்று மகள்', CHULAT_BHAU: 'சகோதரக் உறவினர்', CHULAT_BAHIN: 'சகோதரி உறவினர்',
    MAMI_BHAU: 'மாமா மகன்', MAMI_BAHIN: 'மாமா மகள்', MAV_BHAU: 'மௌசி மகன்', MAV_BAHIN: 'மௌசி மகள்',
    CHULAT_DAJI: 'சகோதரி கணவர்', CHULAT_VAHINI: 'சகோதரர் மனைவி', MAMI_DAJI: 'மாமா மகள் கணவர்', MAMI_VAHINI: 'மாமா மகன் மனைவி', MAV_DAJI: 'மௌசி மகள் கணவர்', MAV_VAHINI: 'மௌசி மகன் மனைவி',
    CHULAT_BHACHA: 'உறவினர் மருமகன்', CHULAT_BHACHI: 'உறவினர் மருமகள்',
    CHULAT_AAJI: 'தந்தை வழி பாட்டி', CHULAT_AATYA_BHAU: 'அத்தை மகன்', CHULAT_AATYA_BAHIN: 'அத்தை மகள்',
    FUA_AJOBA: 'அத்தை மாமா', FAU_AJOBA: 'அத்தை மாமா',
    ATYE_BHAU: 'அத்தை மகன்', ATYE_BAHIN: 'அத்தை மகள்', AJI_SASU: 'பாட்டி மாமியார்', AJI_SASRA: 'தாத்தா மாமனார்',
    CHULTA: 'சித்தப்பா', CHULTI: 'சித்தி', PP_AJOBA: 'முப்பாட்டன்', PP_AAJI: 'முப்பாட்டி', PPP_AJOBA: 'கொள்ளு தாத்தா',
    PPP_AAJI: 'கொள்ளு பாட்டி', AJOBA_SASRA: 'தாத்தா மாமனார்', AJOBA_SASU: 'பாட்டி மாமியார்', MAMA_SASRA: 'மாமா மாமனார்',
    MAMI_SASU: 'மாமி மாமியார்', PANAJI_SASU: 'பெரிய பாட்டி மாமியார்', PANJOBA_SASRA: 'பெரிய தாத்தா மாமனார்',
    CHULAT_SASRA: 'சித்தப்பா மாமனார்', ATYA_SASU: 'அத்தை மாமியார்', MAVAS_SASU: 'மௌசி மாமியார்',
    CHULTA_DIR: 'சகோதர மைத்துனர்', CHULTA_NANAND: 'சகோதரி மைத்துனி', NAT_JAVAI: 'பேரன் மருமகன்',
    NATASUN: 'பேத்தி மருமகள்', PANTU: 'கொள்ளுப் பேரன்', PANTI: 'கொள்ளுப் பேத்தி', PANTISUN: 'கொள்ளுப் பேரன் மனைவி',
    PANTU_JAVAI: 'கொள்ளுப் பேத்தி கணவர்', PP_NATU: 'எள்ளுப் பேரன்', PP_NAAT: 'எள்ளுப் பேத்தி', PPP_NATU: 'முப்பாட்டன் பேரன்', PPP_NAAT: 'முப்பாட்டன் பேத்தி'
  },
  kn: {
    AAI: 'ತಾಯಿ', VADIL: 'ತಂದೆ', AAJI: 'ಅಜ್ಜಿ', AJOBA: 'ಅಜ್ಜ', NANI: 'ನಾನಿ', NANA: 'ತಾತ',
    PANAAJI: 'ಹಿರಿಯ ಅಜ್ಜಿ', PANJOBA: 'ಹಿರಿಯ ಅಜ್ಜ', SASU: 'ಅತ್ತೆ', SASRA: 'ಮಾವ', KAKA: 'ಚಿಕ್ಕಪ್ಪ', KAKI: 'ಚಿಕ್ಕಮ್ಮ',
    MAMA: 'ಮಾಮ', MAMI: 'ಮಾಮಿ', AATYA: 'ಅತ್ತಿಗೆ', FUA: 'ಅತ್ತಿಗೆಯ ಗಂಡ', MAVSHI: 'ಮಾವಸಿ', MAVSA: 'ಮಾವಸ',
    NAVRA: 'ಗಂಡ', BAYKO: 'ಹೆಂಡತಿ', BHAU: 'ಅಣ್ಣ', BAHIN: 'ತಂಗಿ', VAHINI: 'ಅಕ್ಕ', DAJI: 'ಬಾವ',
    MEVHANA: 'ಬಾವ', MEVHANI: 'ಅತ್ತಿಗೆ', DIR_CHOTE: 'ದೇವರ', DIR_MOTHE: 'ಜ್ಯೇಷ್ಠ ದೇವರ', NANAND: 'ನಣಂದೆ',
    NANANDOI: 'ನಣಂದಿಯ ಗಂಡ', MULGA: 'ಮಗ', MULGI: 'ಮಗಳು', JAVAI: 'ಅಳಿಯ', SUN: 'ಸೊಸೆ', PUTANYA: 'ಸೋದರನ ಮಗ',
    PUTANI: 'ಸೋದರನ ಮಗಳು', BHACHA: 'ಸಹೋದರಿಯ ಮಗ', BHACHI: 'ಸಹೋದರಿಯ ಮಗಳು', NATU: 'ಮೊಮ್ಮಗ', NAAT: 'ಮೊಮ್ಮಗಳು',
    MITRA: 'ಸ್ನೇಹಿತ', MAITRIN: 'ಸ್ನೇಹಿತೆ', NATEVAIK: 'ಸಂಬಂಧಿ', SAVATR_VADIL: 'ಸವತಿ ತಂದೆ', SAVATR_AAI: 'ಸವತಿ ತಾಯಿ', SAVATR_BHAU: 'ಸವತಿ ಸಹೋದರ',
    SAVATR_BAHIN: 'ಸವತಿ ಸಹೋದರಿ', SAVATR_MULGA: 'ಸವತಿ ಮಗ', SAVATR_MULGI: 'ಸವತಿ ಮಗಳು', CHULAT_BHAU: 'ಚಿಕ್ಕಪ್ಪನ ಮಗ',
    CHULAT_BAHIN: 'ಚಿಕ್ಕಪ್ಪನ ಮಗಳು', MAMI_BHAU: 'ಮಾಮನ ಮಗ', MAMI_BAHIN: 'ಮಾಮನ ಮಗಳು', MAV_BHAU: 'ಮಾವಸಿಯ ಮಗ',
    MAV_BAHIN: 'ಮಾವಸಿಯ ಮಗಳು',
    CHULAT_DAJI: 'ಚಿಕ್ಕಪ್ಪನ ಮಗಳ ಗಂಡ', CHULAT_VAHINI: 'ಚಿಕ್ಕಪ್ಪನ ಮಗನ ಹೆಂಡತಿ', MAMI_DAJI: 'ಮಾಮನ ಮಗಳ ಗಂಡ', MAMI_VAHINI: 'ಮಾಮನ ಮಗನ ಹೆಂಡತಿ', MAV_DAJI: 'ಮಾವಸಿಯ ಮಗಳ ಗಂಡ', MAV_VAHINI: 'ಮಾವಸಿಯ ಮಗನ ಹೆಂಡತಿ',
    CHULAT_BHACHA: 'ಸಂಬಂಧಿ ಸೋದರಳಿಯ', CHULAT_BHACHI: 'ಸಂಬಂಧಿ ಸೋದರಸೊಸೆ',
    ATYE_BHAU: 'ಅತ್ತಿಗೆಯ ಮಗ', ATYE_BAHIN: 'ಅತ್ತಿಗೆಯ ಮಗಳು', AJI_SASU: 'ಅಜ್ಜಿ ಅತ್ತೆ',
    AJI_SASRA: 'ಅಜ್ಜ ಮಾವ', CHULTA: 'ಚಿಕ್ಕಪ್ಪ', CHULTI: 'ಚಿಕ್ಕಮ್ಮ', PP_AJOBA: 'ಮುತ್ತಜ್ಜ', PP_AAJI: 'ಮುತ್ತಜ್ಜಿ',
    PPP_AJOBA: 'ಮರಿಮುತ್ತಜ್ಜ', PPP_AAJI: 'ಮರಿಮುತ್ತಜ್ಜಿ', AJOBA_SASRA: 'ಅಜ್ಜ ಮಾವ', AJOBA_SASU: 'ಅಜ್ಜಿ ಅತ್ತೆ',
    MAMA_SASRA: 'ಮಾಮ ಮಾವ', MAMI_SASU: 'ಮಾಮಿ ಅತ್ತೆ', PANAJI_SASU: 'ಮುತ್ತಜ್ಜಿ ಅತ್ತೆ', PANJOBA_SASRA: 'ಮುತ್ತಜ್ಜ ಮಾವ',
    CHULAT_SASRA: 'ಚಿಕ್ಕಪ್ಪ ಮಾವ', ATYA_SASU: 'ಅತ್ತಿಗೆ ಅತ್ತೆ', MAVAS_SASU: 'ಮಾವಸಿ ಅತ್ತೆ', CHULTA_DIR: 'ಸಹೋದರ ದೇವರ',
    CHULTA_NANAND: 'ಸಹೋದರಿ ನಣಂದೆ', NAT_JAVAI: 'ಮೊಮ್ಮಗ ಅಳಿಯ', NATASUN: 'ಮೊಮ್ಮಗಳ ಸೊಸೆ', PANTU: 'ಮರಿಮೊಮ್ಮಗ',
    PANTI: 'ಮರಿಮೊಮ್ಮಗಳು', PANTISUN: 'ಮರಿಮೊಮ್ಮಗಳ ಸೊಸೆ', PANTU_JAVAI: 'ಮರಿಮೊಮ್ಮಗ ಅಳಿಯ', PP_NATU: 'ಮುತ್ತಜ್ಜನ ಮೊಮ್ಮಗ',
    PP_NAAT: 'ಮುತ್ತಜ್ಜನ ಮೊಮ್ಮಗಳು', PPP_NATU: 'ಮರಿಮುತ್ತಜ್ಜನ ಮೊಮ್ಮಗ', PPP_NAAT: 'ಮರಿಮುತ್ತಜ್ಜನ ಮೊಮ್ಮಗಳು'
  },
  gu: {
    AAI: 'મા', VADIL: 'પિતા', AAJI: 'દાદી', AJOBA: 'દાદા', NANI: 'નાની', NANA: 'નાના',
    PANAAJI: 'પરદાદી', PANJOBA: 'પરદાદા', SASU: 'સાસુ', SASRA: 'સસરા', KAKA: 'કાકા', KAKI: 'કાકી',
    MAMA: 'મામા', MAMI: 'મામી', AATYA: 'ફોઈ', FUA: 'ફુવા', MAVSHI: 'માસી', MAVSA: 'માસા',
    NAVRA: 'પતિ', BAYKO: 'પત્ની', BHAU: 'ભાઈ', BAHIN: 'બહેન', VAHINI: 'ભાભી', DAJI: 'જીજાજી',
    MEVHANA: 'સાળો', MEVHANI: 'સાળી', DIR_CHOTE: 'દેવર', DIR_MOTHE: 'જેઠ', NANAND: 'નણંદ', NANANDOI: 'નણદોઈ',
    MULGA: 'દીકરો', MULGI: 'દીકરી', JAVAI: 'જમાઈ', SUN: 'વહુ', PUTANYA: 'ભત્રીજો', PUTANI: 'ભત્રીજી',
    BHACHA: 'ભાણેજ', BHACHI: 'ભાણી', NATU: 'પૌત્ર', NAAT: 'પૌત્રી', MITRA: 'મિત્ર', MAITRIN: 'સખી', NATEVAIK: 'સગો/સગી',
    SAVATR_VADIL: 'સાવકા પિતા', SAVATR_AAI: 'સાવકી મા', SAVATR_BHAU: 'સાવકો ભાઈ', SAVATR_BAHIN: 'સાવકી બહેન',
    SAVATR_MULGA: 'સાવકો દીકરો', SAVATR_MULGI: 'સાવકી દીકરી', CHULAT_BHAU: 'કઝિન ભાઈ', CHULAT_BAHIN: 'કઝિન બહેન',
    MAMI_BHAU: 'મામેરો ભાઈ', MAMI_BAHIN: 'મામેરી બહેન', MAV_BHAU: 'માસેરો ભાઈ', MAV_BAHIN: 'માસેરી બહેન',
    CHULAT_DAJI: 'કઝિન જીજાજી', CHULAT_VAHINI: 'કઝિન ભાભી', MAMI_DAJI: 'મામેરો જીજાજી', MAMI_VAHINI: 'મામેરી ભાભી', MAV_DAJI: 'માસેરો જીજાજી', MAV_VAHINI: 'માસેરી ભાભી',
    CHULAT_BHACHA: 'કઝિન ભાણો', CHULAT_BHACHI: 'કઝિન ભાણી',
    ATYE_BHAU: 'ફુફેરો ભાઈ', ATYE_BAHIN: 'ફુફેરી બહેન', AJI_SASU: 'દાદી સાસુ', AJI_SASRA: 'દાદા સસરા',
    CHULTA: 'કાકા', CHULTI: 'કાકી', PP_AJOBA: 'પરદાદા', PP_AAJI: 'પરદાદી', PPP_AJOBA: 'લક્કડ દાદા',
    PPP_AAJI: 'લક્કડ દાદી', AJOBA_SASRA: 'દાદા સસરા', AJOBA_SASU: 'દાદી સાસુ', MAMA_SASRA: 'મામા સસરા',
    MAMI_SASU: 'મામી સાસુ', PANAJI_SASU: 'પરદાદી સાસુ', PANJOBA_SASRA: 'પરદાદા સસરા', CHULAT_SASRA: 'કાકા સસરા',
    ATYA_SASU: 'ફોઈ સાસુ', MAVAS_SASU: 'માસી સાસુ', CHULTA_DIR: 'કઝિન દેવર', CHULTA_NANAND: 'કઝિન નણંદ',
    NAT_JAVAI: 'પૌત્ર જમાઈ', NATASUN: 'પૌત્ર વહુ', PANTU: 'પરપૌત્ર', PANTI: 'પરપૌત્રી', PANTISUN: 'પરપૌત્ર વહુ',
    PANTU_JAVAI: 'પરપૌત્ર જમાઈ', PP_NATU: 'લક્કડ પૌત્ર', PP_NAAT: 'લક્કડ પૌત્રી', PPP_NATU: 'છક્કડ પૌત્ર', PPP_NAAT: 'છક્કડ પૌત્રી'
  },
  te: {
    AAI: 'అమ్మ', VADIL: 'నాన్న', AAJI: 'అమ్మమ్మ', AJOBA: 'తాతయ్య', NANI: 'నానమ్మ', NANA: 'తాతయ్య',
    PANAAJI: 'పెద్దమ్మమ్మ', PANJOBA: 'పెద్దతాతయ్య', SASU: 'అత్త', SASRA: 'మామయ్య', KAKA: 'బాబాయి', KAKI: 'పిన్ని',
    MAMA: 'మామయ్య', MAMI: 'అత్తయ్య', AATYA: 'అత్త', FUA: 'అత్తగారి భర్త', MAVSHI: 'మేనత్త', MAVSA: 'మేనమామ',
    NAVRA: 'భర్త', BAYKO: 'భార్య', BHAU: 'అన్న', BAHIN: 'చెల్లి', VAHINI: 'వదిన', DAJI: 'బావ',
    MEVHANA: 'బావ', MEVHANI: 'మరదలు', DIR_CHOTE: 'దేవర', DIR_MOTHE: 'పెద్ద దేవర', NANAND: 'ననంద', NANANDOI: 'ననంద భర్త',
    MULGA: 'కొడుకు', MULGI: 'కూతురు', JAVAI: 'అల్లుడు', SUN: 'కోడలు', PUTANYA: 'సోదరుని కుమారుడు', PUTANI: 'సోదరుని కుమార్తె',
    BHACHA: 'మేనల్లుడు', BHACHI: 'మేనకోడలు', NATU: 'మనవడు', NAAT: 'మనవరాలు', MITRA: 'స్నేహితుడు', MAITRIN: 'స్నేహితురాలు', NATEVAIK: 'బంధువు',
    SAVATR_VADIL: 'సవతి తండ్రి', SAVATR_AAI: 'సవతి తల్లి', SAVATR_BHAU: 'సవతి అన్న', SAVATR_BAHIN: 'సవతి చెల్లి',
    SAVATR_MULGA: 'సవతి కొడుకు', SAVATR_MULGI: 'సవతి కూతురు', CHULAT_BHAU: 'కజిన్ అన్న', CHULAT_BAHIN: 'కజిన్ చెల్లి',
    MAMI_BHAU: 'మామయ్య కొడుకు', MAMI_BAHIN: 'మామయ్య కూతురు', MAV_BHAU: 'మేనత్త కొడుకు', MAV_BAHIN: 'మేనత్త కూతురు',
    CHULAT_DAJI: 'కజిన్ బావ', CHULAT_VAHINI: 'కజిన్ వదిన', MAMI_DAJI: 'మామయ్య కూతురు భర్త', MAMI_VAHINI: 'మామయ్య కొడుకు భార్య', MAV_DAJI: 'మేనత్త కూతురు భర్త', MAV_VAHINI: 'మేనత్త కొడుకు భార్య',
    CHULAT_BHACHA: 'కజిన్ మేనల్లుడు', CHULAT_BHACHI: 'కజిన్ మేనకోడలు',
    ATYE_BHAU: 'అత్త కొడుకు', ATYE_BAHIN: 'అత్త కూతురు', AJI_SASU: 'అమ్మమ్మ అత్త', AJI_SASRA: 'తాతయ్య మామయ్య',
    CHULTA: 'బాబాయి', CHULTI: 'పిన్ని', PP_AJOBA: 'ముత్తాత', PP_AAJI: 'ముత్తవ్వ', PPP_AJOBA: 'ముత్తాతయ్య',
    PPP_AAJI: 'ముత్తవ్వమ్మ', AJOBA_SASRA: 'తాతయ్య మామయ్య', AJOBA_SASU: 'అమ్మమ్మ అత్త', MAMA_SASRA: 'మామయ్య మామయ్య',
    MAMI_SASU: 'అత్తయ్య అత్త', PANAJI_SASU: 'పెద్దమ్మమ్మ అత్త', PANJOBA_SASRA: 'పెద్దతాతయ్య మామయ్య', CHULAT_SASRA: 'బాబాయి మామయ్య',
    ATYA_SASU: 'అత్త అత్త', MAVAS_SASU: 'మేనత్త అత్త', CHULTA_DIR: 'కజిన్ దేవర', CHULTA_NANAND: 'కజిన్ ననంద',
    NAT_JAVAI: 'మనవడు అల్లుడు', NATASUN: 'మనవరాలు కోడలు', PANTU: 'మునిమనవడు', PANTI: 'మునిమనవరాలు', PANTISUN: 'మునిమనవరాలు కోడలు',
    PANTU_JAVAI: 'మునిమనవడు అల్లుడు', PP_NATU: 'ముత్తాత మనవడు', PP_NAAT: 'ముత్తాత మనవరాలు', PPP_NATU: 'ముత్తాత మునిమనవడు', PPP_NAAT: 'ముత్తాత మునిమనవరాలు'
  }
};

function getSeedLabel(entry, languageCode) {
  if (languageCode === 'mr') return entry.mr || entry.en || entry.code;
  if (languageCode === 'en') return entry.en || entry.mr || entry.code;
  if (languageCode === 'zh') return entry.zh || entry.en || entry.mr || entry.code;
  return relationLanguageOverrides[languageCode]?.[entry.code] || entry.en || entry.mr || entry.code;
}

async function main() {
  console.log('🌱 Seeding ALL MASTER RELATIONS...');

  // Upsert RelationTypes first
  for (const rt of relationTypes) {
    await prisma.relationType.upsert({
      where: { code: rt.code },
      update: rt,
      create: rt,
    });
  }

  // Upsert Translations
  for (const t of translations) {
    for (const languageCode of TRANSLATION_LANGUAGE_CODES) {
      const label = getSeedLabel(t, languageCode);
      if (!label) continue;

      await prisma.relationTranslation.upsert({
        where: {
          relationTypeCode_languageCode_community: {
            relationTypeCode: t.code,
            languageCode,
            community: '',
          },
        },
        update: { label },
        create: {
          relationTypeCode: t.code,
          languageCode,
          community: '',
          label,
        },
      });
    }
  }

  console.log(`✅ Seeded ${relationTypes.length} relations with translations.`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
