// src/controllers/configController.ts
import type { Request, Response } from 'express';
import { gamificationConfig } from '../config/gamification';

/**
 * GET /api/config/gamification
 *
 * Serves the scoring and badge-tier definitions so the clients stop hardcoding
 * their own copies. Previously:
 *  - `web/components/UserTierBadge.tsx` and `mobile/components/ui/UserTierBadge.tsx`
 *    each carried their own BRONZE..DIAMOND colour palette, and the two disagreed
 *    with each other and with the backend's own values.
 *  - both ScoreWidget components hardcoded "+2 / +5 / +20" and the score reason
 *    labels, so changing SCORE_POINTS on the server left the UI lying to users.
 *
 * The payload is identical for every caller, so it is public and heavily cacheable.
 */
export const getGamificationConfig = (_req: Request, res: Response): void => {
  const payload = gamificationConfig();

  // Static reference data: safe for shared caches, and revalidatable via ETag
  // (the ETag itself is generated by the `etag` setting in index.ts).
  res.set('Cache-Control', 'public, max-age=300, stale-while-revalidate=600');
  res.json(payload);
};
