// scripts/clean_stress_seed_data.js
require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const { Pool } = require('pg');

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

async function cleanStressSeedData() {
  console.log('🔍 Identifying stress test fake users...');

  // Identify all fake users generated by stress_seeder (they have @samajunati.com email and phone != 9999999999)
  const fakeUsers = await prisma.user.findMany({
    where: {
      email: { contains: 'samajunati.com' },
      phone: { not: '9999999999' },
    },
    select: { id: true },
  });

  const fakeUserIds = fakeUsers.map((u) => u.id);
  console.log(`Found ${fakeUserIds.length} fake stress-test users to remove.`);

  const rootUser = await prisma.user.findFirst({
    where: { phone: '9999999999' },
  });

  const allTargetIds = rootUser ? [...fakeUserIds, rootUser.id] : fakeUserIds;

  // 1. Delete all relations involving fake users or root user
  console.log('🧹 Deleting relations associated with fake users and test root user...');
  const deletedRels = await prisma.relation.deleteMany({
    where: {
      OR: [
        { fromUserId: { in: allTargetIds } },
        { toUserId: { in: allTargetIds } },
        { createdById: { in: allTargetIds } },
      ],
    },
  });
  console.log(`Deleted ${deletedRels.count} relations.`);

  if (fakeUserIds.length > 0) {
    // 2. Notifications & Scores
    const deletedNotifs = await prisma.notification.deleteMany({
      where: { userId: { in: allTargetIds } },
    });
    const userScores = await prisma.userScore.findMany({
      where: { userId: { in: allTargetIds } },
      select: { id: true },
    });
    const userScoreIds = userScores.map((s) => s.id);
    let deletedScoreEventsCount = 0;
    let deletedScoresCount = 0;
    if (userScoreIds.length > 0) {
      const deletedEvents = await prisma.scoreEvent.deleteMany({
        where: { userId: { in: userScoreIds } },
      });
      deletedScoreEventsCount = deletedEvents.count;
      const deletedScores = await prisma.userScore.deleteMany({
        where: { id: { in: userScoreIds } },
      });
      deletedScoresCount = deletedScores.count;
    }
    console.log(`Deleted notifications (${deletedNotifs.count}), score events (${deletedScoreEventsCount}), user scores (${deletedScoresCount}).`);

    // 3. Messages & Conversations
    const deletedMsgReads = await prisma.messageRead.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    const deletedMsgs = await prisma.message.deleteMany({
      where: { senderId: { in: fakeUserIds } },
    });
    const deletedConvMembers = await prisma.conversationMember.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    console.log(`Deleted messages (${deletedMsgs.count}), reads (${deletedMsgReads.count}), members (${deletedConvMembers.count}).`);

    // Clean up empty conversations
    const emptyConvs = await prisma.conversation.findMany({
      where: {
        members: { none: {} },
      },
      select: { id: true },
    });
    if (emptyConvs.length > 0) {
      await prisma.conversation.deleteMany({
        where: { id: { in: emptyConvs.map((c) => c.id) } },
      });
      console.log(`Deleted ${emptyConvs.length} empty conversations.`);
    }

    // 4. Social: Posts, Comments, Likes, Shares, Media
    const deletedComments = await prisma.postComment.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    const deletedLikes = await prisma.postLike.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    const deletedShares = await prisma.postShare.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    const deletedMedia = await prisma.postMedia.deleteMany({
      where: { post: { userId: { in: fakeUserIds } } },
    });
    const deletedPosts = await prisma.post.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    console.log(`Deleted posts (${deletedPosts.count}), media (${deletedMedia.count}), comments (${deletedComments.count}), likes (${deletedLikes.count}), shares (${deletedShares.count}).`);

    // 5. Stories
    const deletedStoryViews = await prisma.storyView.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    const deletedStories = await prisma.story.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });
    console.log(`Deleted stories (${deletedStories.count}), story views (${deletedStoryViews.count}).`);

    // 6. Follows & Blocks
    const deletedFollows = await prisma.follow.deleteMany({
      where: {
        OR: [
          { followerId: { in: fakeUserIds } },
          { followingId: { in: fakeUserIds } },
        ],
      },
    });
    const deletedBlocks = await prisma.userBlock.deleteMany({
      where: {
        OR: [
          { blockerId: { in: fakeUserIds } },
          { blockedId: { in: fakeUserIds } },
        ],
      },
    });
    console.log(`Deleted follows (${deletedFollows.count}), blocks (${deletedBlocks.count}).`);

    // 7. Push Tokens & other user constraints
    await prisma.pushToken.deleteMany({
      where: { userId: { in: fakeUserIds } },
    });

    // 8. Delete fake users in batches of 500
    console.log(`Deleting ${fakeUserIds.length} fake users...`);
    const batchSize = 500;
    for (let i = 0; i < fakeUserIds.length; i += batchSize) {
      const batch = fakeUserIds.slice(i, i + batchSize);
      await prisma.user.deleteMany({
        where: { id: { in: batch } },
      });
      console.log(`Deleted batch ${Math.floor(i / batchSize) + 1} / ${Math.ceil(fakeUserIds.length / batchSize)}`);
    }
  }

  // 9. Reset or clean up the root bypass user 9999999999
  if (rootUser) {
    console.log('Resetting test bypass user 9999999999 to clean standalone registration...');
    await prisma.user.update({
      where: { id: rootUser.id },
      data: {
        firstName: 'Google',
        lastName: 'Reviewer',
        email: null,
        phone: '9999999999',
        gender: 'MALE',
        religion: 'Hindu',
        community: 'General',
        caste: null,
        subcaste: null,
        profileCompleted: true,
        isRegistered: true,
        isAlive: true,
        isPrivate: false,
        worldX: 0,
        worldY: 0,
        appLanguage: 'en',
        relationLanguage: 'en',
      },
    });
    console.log('Test bypass user 9999999999 reset successfully with 0 members.');
  }

  // 10. Audit remaining counts
  const finalUserCount = await prisma.user.count();
  const finalRelCount = await prisma.relation.count();
  console.log('\n--- CLEANUP COMPLETE ---');
  console.log(`Remaining Users in DB: ${finalUserCount}`);
  console.log(`Remaining Relations in DB: ${finalRelCount}`);
}

cleanStressSeedData()
  .catch((e) => {
    console.error('Error during cleanup:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
